---
title: "R Notebook"
output: html_notebook
---

```{r}
source("common_functions_media.R")
source("stat_functions.R")
source("plotting_functions.R")

t0p1_file<-"figure 4/ethanol_36h/" #180515
t1p1_file<-"figure 4/glycerol_48h/" #180515
t2p1_file<-"figure 4/proline_43h/" #180504
t6p1_file<-"figure 4/sd_6h/" # 180518
t3p1_file<-"figure 4/ethanol_36h/controls" #180515
t4p1_file<-"figure 4/glycerol_48h/controls" #180515
t5p1_file<-"figure 4/proline_43h/controls"  #180504
t7p1_file<-"figure 4/sd_6h/controls" # 180518
pattern_read<-"Specimen_001"


output_path<-"C:/Users/aslia/Desktop/pisi/ETH/master project/labbook/paper/figures/figure4/drm_package"
# create folders named size, svf, histograms, boxplots under this directory. 

starting_well<-1
wells_per_sample<-24


ypethanol_doses<-c(0,0.5,1,3,5,8,12,15,17,21,23,25,30,35,40,50,60,75,100,150,200,300,400,600)
glycerol_doses<-c(0,0.2,0.5,1,2,4,5,7,8,10,12,14,16,18,20,25,27,30,45,60,100,200,400,600)
proline_doses<-c(0,0.2,0.5,0.7,1,1.5,2,2.5,3,4,6,8,10,12,15,20)
#25,30,40,45,60,200,400,600
sd_doses<- c(0,0.5,1,3,5,8,12,15,17,21,23,25,30,35,40,50,60,75,100,150,200,300,400,600)
experiment_doses<-list(ypethanol_doses,c(0,max(ypethanol_doses)),
                       c(0,max(ypethanol_doses)),c(0,max(ypethanol_doses)),
                       glycerol_doses, c(0,600),c(0,600),c(0,600),
                       proline_doses, c(0,600),c(0,600),c(0,600),
                       sd_doses,c(0,600),c(0,600),c(0,600))


columns_to_include<-c(2,5,3,6,7) #1=FSC-A, #2=FSC-H, #3=FSC-W, #4=SSC-A, #5=SSC-H, #6=SSC-W, #7= 488 [C]-H

strain_names<-c("2759eth","2661eth","2683eth","70eth",
                "2759gly","2661gly","2683gly","70gly",
                "2759pro","2661pro","2683pro","70pro",
                "2759sd","2661sd","2683sd","70sd"
                ) 
time_points<-c("24h")

label_list<- c("7op NF_eth",
               "no repressor_eth",
               "tdh3_eth",
               "fry70_eth",
               "7op NF_gly","tdh3_gly",
               "fry70_gly",
               "no repressor_gly",
               "7op NF_pro",
               "no repressor_pro",
               "tdh3_pro",
               "fry70_pro",
               "7op NF_sd",
               "no repressor_sd",
               "tdh3_sd",
               "fry70_sd"
               )

names(label_list)<-strain_names

xlabel<-"aTc [ng/mL]"

#---------------------------------------------------------------------------------------------------------------
## pick the values to subset the data with. 

columns <-c(3:6) #columns to be included in the subset
col_fscw <- 1 #column of FSC-W/H
col_sscw <- 2 #column of SSC-W/H
limit_fscw <-250000 #the value for subsetting based on FSC-W/H
limit_sscw <-250000 #the value for subsetting based on SSC-W/H
lower_limit_fscw <-10000 #the value for subsetting based on FSC-W/H, lower limit
lower_limit_sscw <-0000 #the value for subsetting based on SSC-W/H, lower limit

size_subset<-TRUE # set to TRUE if you want to use size_subsetted data, otherwise false.

#----------------------------------------------------------------------------------------------------------
## descriptive statistics

dose_descriptives<-experiment_doses
cols_descriptives<-3



```


```{r overlaid plotting function}
# creating the individual plots
library("minpack.lm")
library("ggthemes")
library("ggplot2")
## plotting the sigmoid curves.
xlabel<-expression(paste("aTc [ng/mL]"))


f_sigmoid <- function(params, x) {
  b<-params[[1]]
  c<-params[[2]]
  d<-params[[3]]
  e<-params[[4]]
  p1<-params[[5]]
  p2<-params[[6]]
  
  (c + (d-c)/(1+ exp((b*(log(x+1))^p1)+(e*(log(x+1))^p2)))) #fplogistic
}

f_sigmoid_fit<-function(params,x_values){    
  print(params)
  sigmoid_fit <- f_sigmoid(params,x_values)
 
  return(sigmoid_fit)
}



f_plot_sigmoid_curves_overlaid<-
  # plot the fitted line and the individual data points. 
  function(fit_list,frame_list, control_frame_list,label_list_control, xlim, ylim,control_doses){
    formatter<-function(x){x/1000}
    final_plot<-ggplot() 
    # plot the lines
    for (i in c(1:length(fit_list))){
      single_layer_line<- geom_line(aes_(x=x_values_list[[i]], y=fit_list[[i]],
                                         colour=label_list_sigmoid[[i]]), size=1)
      final_plot<-final_plot+single_layer_line
    }
    
    # plot the individual data points
    for (j in c(1:length(frame_list))){
      single_layer_point<- geom_point(aes_(x=frame_list[[j]][,8],y=frame_list[[j]][,1],
                                           colour=label_list_sigmoid[[j]]))   
      final_plot<-final_plot+single_layer_point
    }
    
    
    
    # plot the controls
    
    # for(k in c(1:length(control_frame_list))){
    #   dose_control<-control_doses[[k]]
    #   frame<-control_frame_list[[k]][which(control_frame_list[[k]][,8]==dose_control),]
    # 
    #   single_layer_control<- geom_hline(aes_(yintercept=frame[,1],
    #                                          linetype=label_list_control[[k]],colour=
    #                                            label_list_sigmoid[[ceiling(k/2)]]))
    #   ribbon_layer_control<- geom_ribbon(aes_(ymin=frame[,1]-(frame[,6]*frame[,1]),
    #                                           ymax=frame[,1]-(frame[,6]*frame[,1]),
    #                                           x=x_values))

      #final_plot<-final_plot+single_layer_control

    #}
    
    
    
    pretty_plot<-final_plot +
      scale_linetype_manual(values=c("longdash","dotdash",
                                     "longdash","dotdash",
                                     "longdash","dotdash",
                                     "longdash","dotdash")) +

     scale_colour_manual(values = colour_palette) +
     scale_x_continuous(breaks = x_axis_breaks,
                   labels = x_axis_labels,
                   limits = xlim) +
                   # trans = "log10") +
     scale_y_continuous(limits = ylim,  breaks=c(0,10000,20000,30000,40000,50000), labels=formatter) +
      guides(colour=guide_legend(title = "Media",ncol=4)) +
      # ggtitle(plot_title) +
      xlab(xlabel) +
      ylab(expression(paste("Fluorescence x","10"^"3","(a.u.)",sep="")))+
      theme(panel.grid.minor = element_blank(),
            legend.position = "top", 
            legend.direction = "horizontal",
            # legend.title = element_blank(),
            legend.key.height = unit(0.35,"cm"),
            legend.key = element_blank(),
            legend.box.background = element_rect(linetype = "solid", colour="black"),
            legend.margin = margin(t=0.04,r=0.1,b=0.1,l=0.1,unit="cm"),
            panel.border = element_blank(),
             axis.line = element_line(),
            # axis.text = element_text(size=24),
            # axis.title = element_text(size=24),
            axis.title = element_text(hjust = 1),
            panel.background = element_blank()
            )
    
    return(pretty_plot)
  }

```




```{r derivative plotting function}
f_fit_function<-function(x) (c + (d-c)/(1+ exp((b*(log(x+1))^p1)+(e*(log(x+1))^p2)))) #fplogistic function
d_fit_function<-D(body(f_fit_function),'x')

f_d_sigmoid <- function(params, x) {
  
  b<-params[[1]]
  c<-params[[2]]
  d<-params[[3]]
  e<-params[[4]]
  p1<-params[[5]]
  p2<-params[[6]]
  
  eval(D(body(f_fit_function),'x'))
  
  
}


f_d_sigmoid_fit<-function(params,x_values_d){    
  sigmoid_fit <- f_d_sigmoid(params,x_values_d)
  return(sigmoid_fit)
}

f_plot_sigmoid_d<-function( y_values, label_list,ylims){
  
  final_plot<- ggplot() 
  
  for(i in c(1:length(y_values))){
    single_layer<-geom_line(aes_(x=x_values_d_list[[i]],y=y_values[[i]], colour=label_list[[i]]), size=1)
    final_plot<-final_plot+single_layer
  }
  
  
  pretty_plot<-final_plot +
    guides(colour=guide_legend(title = "")) +
    ylab("Slope") +
    scale_colour_manual(values = colour_palette) +
    xlab(xlabel) +
    scale_x_continuous(breaks = breaks_x_axis_d,
                    labels = labels_x_axis_d,
                    limits = c(0.19,200), 
                    trans = "log10") +
    scale_y_continuous(limits=ylims, breaks = c(0,1500,3000,4500))+
    theme(panel.grid.minor = element_blank(),
            legend.direction = "horizontal",
            legend.position = "none",
            panel.border = element_blank(),
             axis.line = element_line(),
            # axis.text = element_text(size=24),
            # axis.title = element_text(size=24),
            axis.title = element_text(hjust = 1 ),
            panel.background = element_blank()
            )
  
  return(pretty_plot)
}

```

```{r spearman plot}
f_sigmoid_spearman <- function(params, x) {
  b<-params[[1]]
  c<-params[[2]]
  d<-params[[3]]
  e<-params[[4]]
  f<-params[[5]]
  a<-params[[6]]
  
  c + (d-c + f*exp(-1/(x^{a})))/(1+exp(b*(log(x)-log(e))))
  
}

f_sigmoid_fit_spearman<-function(params,x_values){ 
  # takes the parameters for the best fit, any number of x values, and returns a list of y values
  # for plotting. 
  sigmoid_fit <- f_sigmoid_spearman(params,x_values)
  print(params)
  return(sigmoid_fit)
}

# plotting spearman correlation between size and fluorescence. 


#########

f_spearman_fit_plot<-function(fit,label,data){
  
  final_plot<-ggplot() 
    
    for(i in c(1:length(fit))){
      
    single_layer<-geom_line(aes_(x=x_values_spearman_list[[i]],y=fit[[i]], colour=label[[i]])) 
    data_layer<-geom_point(aes_(x=data[[i]][,2], y=data[[i]][,1], colour=label[[i]])) 
    final_plot<-final_plot+single_layer
    final_plot<-final_plot+data_layer
    
    }
    
    
  
  pretty_plot<- final_plot +
     ylab("Spearman Correlation") +
    scale_colour_manual(values = colour_palette) +
    scale_linetype_manual(values=c("longdash", "dotdash")) +
    xlab(xlabel) +
    scale_x_continuous(breaks = c(0.19,1,10,50,200),
                    labels =  c(0,1,10,50,200), 
                    limits = xlim_spearman,
                    trans = "log10") +
    scale_y_continuous(limits=c(0.40,0.85), breaks = c(0.4,0.5,0.6,0.7,0.8,0.9)) +
    theme(panel.grid.minor = element_blank(),
            legend.direction = "horizontal", legend.position = "none", 
            panel.border = element_blank(), 
             axis.line = element_line(),
            # axis.text = element_text(size=24),
            # axis.title = element_text(size=24),
            axis.title = element_text(hjust = 1 ),
            panel.background = element_blank()
            ) 
  
  
  return(pretty_plot)
  
}


```



```{r overlaid ethanol, glycerol, proline,sd}

list_p1<-list(-0.8,-0.8,-0.8,-0.8)

list_p2<-list(3,3,3,3)


list_formulas<-list()

for(i in c(1:length(list_p1))){
  formula<- fplogistic(p1=list_p1[[i]],p2=list_p2[[i]])
  list_formulas[[i]]<-formula
}


#--------------------------------------------------------------------------------------------------

descriptives_to_use<-c(1,5,9,13)
control_descriptives_to_use<-c(2,3,4,6,7,8,10,11,12,14,15,16)
xlim<-c(0,200)
ylim<-c(0,50000)
dose_control<-c("400","400","200","200","200","200","400","400")

colour_palette<-c("#7a1f1f","#cb3434","#ff3333","#ffcccc")

# pick which strains/time_points you want to plot, and their labels
frame_list<-descriptives[descriptives_to_use]
label_list_sigmoid<-c("YPeth","SGly","SDpro","SDmin")
label_list_control<-c("ype_norepressor","ype_70",
                      "gly_norepressor","gly_70",
                      "pro_norepressor","pro_70",
                      "sd_norepressor","sd_70")

control_frame_error<-df_list[control_descriptives_to_use]
# pick your controls
control_frame_list<-descriptives[control_descriptives_to_use]



#define x axis doses and the labels for plotting
doses_experiment<-c(0,1,5,20,60,200,600)
labels_x_axis<- c("0","1","5","20","60","200","600")


# # replace 0 values in the doses with 0.1
# for(i in c(1:length(frame_list))){
#   frame_list[[i]][1,8]<-0.19
# }


strain_list<-label_list_sigmoid


new_frame_list<-list()

for(i in c(1:length(frame_list))){
  new_frame<-frame_list[[i]][c(1,8)]
  #new_frame[,2]<-log10(new_frame[,2])
  new_frame_list[[i]]<-new_frame
} # creates the dataframes that the drm function can take as input (y values in first column, doses/x values in second column)

# generate log distributed x values for smoother line fitting. 
library(emdbook)
x_values<-seq(min(new_frame_list[[1]][,2]),
               600,length.out = 10000)
x_values_proline<-seq(min(new_frame_list[[1]][,2]),
               30,length.out = 10000)

x_values_list<-list(x_values,x_values,x_values_proline,x_values)
# apply the drm function 

lower_limits<-c(list(c(0,NA,0,NA),
                     c(0,NA,NA,NA),
                     c(NA,NA,10,NA),
                     c(0,NA,NA,NA)))

drm_model<-mapply(drm,data=new_frame_list,fct=list_formulas, lowerl=lower_limits, 
                  MoreArgs = list(logDose=NULL) , SIMPLIFY = F) # the lower bound for the second 

plot(drm_model[[1]], ylim=c(0,60000), xlim=c(0,600), log="x")
plot(drm_model[[2]], ylim=c(0,60000), xlim=c(0,600), log="x")
plot(drm_model[[3]], ylim=c(0,100000), xlim=c(0,600), log="x")
plot(drm_model[[4]], ylim=c(0,60000), xlim=c(0,600), log="x")


parameters<-list()

for(i in c(1:length(drm_model))){
  parameter<-drm_model[[i]]$coefficients
  parameters[[i]]<-c(parameter, list_p1[[i]], list_p2[[i]])
  
}

sigmoid_fit_descriptives<-mapply(f_sigmoid_fit,parameters, x_values_list, SIMPLIFY =F)

x_axis_breaks<-c(0,20,60,100,200)
x_axis_labels<-c(0,20,60,100,200)
sigmoid_plot<-f_plot_sigmoid_curves_overlaid(sigmoid_fit_descriptives,frame_list, control_frame_list,
                                    label_list_control, xlim, ylim, dose_control)

sigmoid_plot 

sigmoid_plot_zoom<-sigmoid_plot + scale_x_continuous(limits = c(0,50), breaks = c(0,10,30,50)) +
  theme(legend.position = "none") 

sigmoid_plot_zoom


ggsave(sigmoid_plot + xlab("") + ylab(""),filename =  "overlaid.jpeg", path=output_path, height=6, width=9.04, units = "cm")
ggsave(sigmoid_plot + xlab("") + ylab(""),filename =  "overlaid.pdf", path=output_path, height=6, width=9.04, units = "cm")

ggsave(sigmoid_plot_zoom+ylab(""),filename =  "overlaid_zoom.jpeg", path=output_path, height=6, width=9.04, units = "cm")
ggsave(sigmoid_plot_zoom+ylab(""),filename =  "overlaid_zoom.pdf", path=output_path, height=6, width=9.04, units = "cm")



#---------------------------------------------------------------------------------------------------
## derivative plot

breaks_x_axis_d<-c(0.19,1,10,50,200)
labels_x_axis_d<-c(0,1,10,50,200)

x_values_d<-lseq(0.19,
               200,length.out=10000)

x_values_d_proline<-lseq(0.19,
               30,length.out=10000)

x_values_d_list<-list(x_values_d,x_values_d,x_values_d_proline,x_values_d)

sigmoid_d_fit<-mapply(f_d_sigmoid_fit,parameters,x_values_d_list, SIMPLIFY = F)

ylims<-c(0,4500)
derivative_plot<-f_plot_sigmoid_d(sigmoid_d_fit, label_list_sigmoid, ylims)

derivative_plot

ggsave(derivative_plot+ylab(""),filename =  "overlaid_derivative.jpeg", path=output_path, height=6, width=9.04
       , units = "cm")

ggsave(derivative_plot+ylab(""),filename =  "overlaid_derivative.pdf", path=output_path, height=6, width=9.04
       , units = "cm")


#---------------------------------------------------------------------------------------------------
## spearman plot
spearman_dfs<-descriptives_to_use
label_list_spearman<-label_list_sigmoid


spearman_list<-df_with_size[spearman_dfs]

# replace 0 values in the doses with 0.19
for(i in c(1:length(spearman_list))){
  for(k in c(1:nrow(spearman_list[[i]]))){
    if(spearman_list[[i]][k,4]== 0){
      spearman_list[[i]][k,4]<-0.19
    }
  }
}

spearman_doses_list<-list(unique(spearman_list[[1]][,4]),unique(spearman_list[[2]][,4]),
                     unique(spearman_list[[3]][,4]),unique(spearman_list[[4]][,4]))

variances<-vector("list",length(spearman_list))

for(k in c(1:length(spearman_list))){
  variance<-vector()
  spearman_doses<-spearman_doses_list[[k]]
  for(i in spearman_doses){
    dataframe<-spearman_list[[k]][which(spearman_list[[k]][,4]==i),]
    var<-cor(dataframe[,3],dataframe[,5], method = "spearman")
    variance<-c(variance,var)
    
  }
  variances[[k]]<-variance
}


spearman_frames<-list()

for(i in c(1:length(spearman_doses_list))){
  dose_column<-spearman_doses_list[[i]]
  spearman_values<-variances[[i]]
  dataframe<-as.data.frame(cbind(spearman_values,dose_column))
  spearman_frames[[i]]<-dataframe
  
}


formula_logistic_spearman<-CRS.6(method="1")

drm_model_spearman<-lapply(spearman_frames,drm,fct=formula_logistic_spearman,logDose=NULL)
plot(drm_model_spearman[[1]], ylim=c(0.40,0.90))
plot(drm_model_spearman[[2]], ylim=c(0.40,0.90))
plot(drm_model_spearman[[3]], ylim=c(0.40,0.90))
plot(drm_model_spearman[[4]], ylim=c(0.40,0.90))


parameters_spearman<-list() 

for(i in c(1:length(drm_model_spearman))){
  parameter<-drm_model_spearman[[i]]$coefficients
  parameters_spearman[[i]]<-parameter
}

x_values_spearman<-lseq(0.19,600,length.out = 10000)
x_values_spearman_proline<-lseq(0.19,30,length.out = 10000)

x_values_spearman_list<-list(x_values_spearman,x_values_spearman,x_values_spearman_proline,x_values_spearman)

spearman_fit<-mapply(f_sigmoid_fit_spearman,parameters_spearman,x_values_spearman_list,SIMPLIFY = F)


xlim_spearman<-c(0.19,200)
spearman<-f_spearman_fit_plot(spearman_fit,label_list_sigmoid,spearman_frames)

spearman

ggsave(spearman+ylab(""),filename =  "overlaid_spearman.jpeg", path=output_path,height=6, width=9.04, units = "cm")
ggsave(spearman+ylab(""),filename =  "overlaid_spearman.pdf", path=output_path,height=6, width=9.04, units = "cm")




```




```{r}

number<-9
dose<-4
a<-subset(df_with_size[[number]],df_with_size[[number]][,dose]==600)
b<-subset(df_with_size[[number]],df_with_size[[number]][,dose]==150)
c<-subset(df_with_size[[number]],df_with_size[[number]][,dose]==60)
d<-subset(df_with_size[[number]],df_with_size[[number]][,dose]==5)
e<-subset(df_with_size[[number]],df_with_size[[number]][,dose]==0.5)


size<-5
flu<-3
ggplot() +
  geom_point(aes(x=a[,size],y=a[,flu]), colour="red") +
  geom_point(aes(x=b[,size],y=b[,flu]), colour="blue") +
  geom_point(aes(x=c[,size],y=c[,flu]), colour="purple") +
  geom_point(aes(x=d[,size],y=d[,flu]), colour="orange") +
  geom_point(aes(x=e[,size],y=e[,flu])) +
  scale_x_log10()


ggplot() +
  geom_point(aes(x=a[,1],y=a[,2]))

```

