---
title: "R Notebook"
output: html_notebook
---

```{r}
source("common_functions_media.R")
source("stat_functions.R")
source("plotting_functions.R")

t0p1_file<-"figure 4/ethanol_36h/" #180515
t1p1_file<-"figure 4/glycerol_48h/" #180515
t2p1_file<-"figure 4/proline_26h/" #180504
t6p1_file<-"figure 4/sd_6h/" # 180518
t3p1_file<-"figure 4/ethanol_36h/controls" #180515
t4p1_file<-"figure 4/glycerol_48h/controls" #180515
t5p1_file<-"figure 4/proline_26h/controls"  #180504
t7p1_file<-"figure 4/sd_6h/controls" # 180518
pattern_read<-"Specimen_001"


output_path<-"C:/Users/aslia/Desktop/pisi/ETH/master project/labbook/paper/figures/figure4"
# create folders named size, svf, histograms, boxplots under this directory. 

starting_well<-1
wells_per_sample<-24


ypethanol_doses<-c(0,0.5,1,3,5,8,12,15,17,21,23,25,30,35,40,50,60,75,100,150,200,300,400,600)
glycerol_doses<-c(0,0.2,0.5,1,2,4,5,7,8,10,12,14,16,18,20,25,27,30,45,60,100,200,400,600)
proline_doses<-c(0,0.2,0.5,0.7,1,1.5,2,2.5,3,4,6,8,10,12,15,20,25,30,40,45,60,200,400,600)
sd_doses<- c(0,0.5,1,3,5,8,12,15,17,21,23,25,30,35,40,50,60,75,100,150,200,300,400,600)
experiment_doses<-list(ypethanol_doses,c(0,max(ypethanol_doses)),
                       c(0,max(ypethanol_doses)),c(0,max(ypethanol_doses)),
                       glycerol_doses, c(0,600),c(0,600),c(0,600),
                       proline_doses, c(0,600),c(0,600),c(0,600),
                       sd_doses,c(0,600),c(0,600),c(0,600))


columns_to_include<-c(2,5,3,6,7) #1=FSC-A, #2=FSC-H, #3=FSC-W, #4=SSC-A, #5=SSC-H, #6=SSC-W, #7= 488 [C]-H

strain_names<-c("2759eth","2661eth","2683eth","70eth",
                "2759gly","2661gly","2683gly","70gly",
                "2759pro","2661pro","2683pro","70pro",
                "2759sd","2661sd","2683sd","70sd"
                ) 
time_points<-c("24h")

label_list<- c("7op NF_eth",
               "no repressor_eth",
               "tdh3_eth",
               "fry70_eth",
               "7op NF_gly","tdh3_gly",
               "fry70_gly",
               "no repressor_gly",
               "7op NF_pro",
               "no repressor_pro",
               "tdh3_pro",
               "fry70_pro",
               "7op NF_sd",
               "no repressor_sd",
               "tdh3_sd",
               "fry70_sd"
               )

names(label_list)<-strain_names

xlabel<-"aTc [ng/mL]"

#---------------------------------------------------------------------------------------------------------------
## pick the values to subset the data with. 

columns <-c(3:6) #columns to be included in the subset
col_fscw <- 1 #column of FSC-W/H
col_sscw <- 2 #column of SSC-W/H
limit_fscw <-250000 #the value for subsetting based on FSC-W/H
limit_sscw <-250000 #the value for subsetting based on SSC-W/H
lower_limit_fscw <-10000 #the value for subsetting based on FSC-W/H, lower limit
lower_limit_sscw <-0000 #the value for subsetting based on SSC-W/H, lower limit

size_subset<-TRUE # set to TRUE if you want to use size_subsetted data, otherwise false.

#----------------------------------------------------------------------------------------------------------
## descriptive statistics

dose_descriptives<-experiment_doses
cols_descriptives<-3



```


```{r overlaid plotting function}
# creating the individual plots
library("minpack.lm")
library("ggthemes")
library("ggplot2")
## plotting the sigmoid curves.
xlabel<-expression(paste("aTc [ng/mL]"))

f_plot_sigmoid_curves_overlaid<-
  # plot the fitted line and the individual data points. 
  function(fit_list,frame_list, control_frame_list,label_list_control, xlim, ylim,control_doses){
    formatter<-function(x){x/1000}
    final_plot<-ggplot() 
    # plot the lines
    for (i in c(1:length(fit_list))){
      single_layer_line<- geom_line(aes_(x=x_values, y=fit_list[[i]],
                                         colour=label_list_sigmoid[[i]]), size=1)
      final_plot<-final_plot+single_layer_line
    }
    
    # plot the individual data points
    for (j in c(1:length(frame_list))){
      single_layer_point<- geom_point(aes_(x=frame_list[[j]][,8],y=frame_list[[j]][,1],
                                           colour=label_list_sigmoid[[j]]))   
      final_plot<-final_plot+single_layer_point
    }
    
    ## find the ECs
    
     for(l in c(1:length(ec_list))){
      ec10<-round(ec_list[[l]][1],1)
      ec10_xvalue<-mean(which(round(x_values,1)==ec10))
      ec10_yvalue<-fit_list[[l]][as.integer(ec10_xvalue)]
      
      ec50<-round(ec_list[[l]][2],1)
      ec50_xvalue<-mean(which(round(x_values,1)==ec50))
      ec50_yvalue<-fit_list[[l]][as.integer(ec50_xvalue)]
      
      ec90<-round(ec_list[[l]][3],0)
      ec90_xvalue<-mean(which(round(x_values,0)==ec90))
      ec90_yvalue<-fit_list[[l]][as.integer(ec90_xvalue)]
      
      
      ec_size<-1.5
       ec10_layer<-geom_point(aes_(x=ec10,
                                 y=ec10_yvalue,
                                 shape=paste("EC10"),
                                 colour=label_list_sigmoid[[l]]),size=ec_size) 
      ec50_layer<-geom_point(aes_(x=ec50,
                                 y=ec50_yvalue,
                                 shape=paste("EC50"),
                                 colour=label_list_sigmoid[[l]]),size=ec_size) 
      ec90_layer<-geom_point(aes_(x=ec90,
                                 y=ec90_yvalue,
                                 shape=paste("EC90"),
                                 colour=label_list_sigmoid[[l]]),size=ec_size)
      
      #final_plot<-final_plot + ec10_layer + ec50_layer + ec90_layer
      
    }
    
    # plot the controls
    
    # for(k in c(1:length(control_frame_list))){
    #   dose_control<-control_doses[[k]]
    #   frame<-control_frame_list[[k]][which(control_frame_list[[k]][,8]==dose_control),]
    # 
    #   single_layer_control<- geom_hline(aes_(yintercept=frame[,1],
    #                                          linetype=label_list_control[[k]],colour=
    #                                            label_list_sigmoid[[ceiling(k/2)]]))
    #   ribbon_layer_control<- geom_ribbon(aes_(ymin=frame[,1]-(frame[,6]*frame[,1]),
    #                                           ymax=frame[,1]-(frame[,6]*frame[,1]),
    #                                           x=x_values))

      #final_plot<-final_plot+single_layer_control

    #}
    
    
    
    pretty_plot<-final_plot +
      scale_shape_manual(values = c("EC10"=0,
                                    "EC50"=1,
                                    "EC90"=2)) +
      scale_linetype_manual(values=c("longdash","dotdash",
                                     "longdash","dotdash",
                                     "longdash","dotdash",
                                     "longdash","dotdash")) +

     scale_colour_manual(values = colour_palette) +
     scale_x_continuous(breaks = doses_experiment,
                   labels = labels_x_axis,
                   limits = xlim,
                   trans = "log10") +
     scale_y_continuous(limits = ylim, labels=formatter) +
      guides(colour=guide_legend(title = "Strains",nrow=4)) +
      # ggtitle(plot_title) +
      xlab(xlabel) +
      ylab(expression(paste("Fluorescence x","10"^"3","(a.u.)",sep="")))+
      theme(panel.grid.minor = element_blank(),
            legend.position = c(0.2,0.7), 
            legend.title = element_blank(),
            legend.key.height = unit(0.35,"cm"),
            legend.key = element_blank(),
            legend.box.background = element_rect(linetype = "solid", colour="black"),
            legend.margin = margin(t=0.04,r=0.1,b=0.1,l=0.1,unit="cm"),
            panel.border = element_blank(),
             axis.line = element_line(),
            # axis.text = element_text(size=24),
            # axis.title = element_text(size=24),
            axis.title = element_text(hjust = 1),
            panel.background = element_blank()
            )
    
    return(pretty_plot)
  }

```




```{r derivative plotting function}
f_fit_function<-function(x) (e + (a-e)/((1 + ((((x/c)^b))^(d)))))
d_fit_function<-D(body(f_fit_function),'x')

f_d_sigmoid <- function(params, x) {
  -((params[1] - params[5]) * ((1 + ((x/params[3])^params[2]))^((params[4]) - 1) * 
                                 ((params[4]) * ((x/params[3])^(params[2] - 1) * 
                                                   (params[2] * (1/params[3])))))/((1 +
                                                                                      ((x/params[3])^params[2]))^
                                                                                     (params[4]))^2)
}


f_d_sigmoid_fit<-function(params,x_values_d){    
  sigmoid_fit <- f_d_sigmoid(params,x_values_d)
  return(sigmoid_fit)
}

f_plot_sigmoid_d<-function(x_values_d, y_values, label_list,ylims,y_value_list,strains){
  
  final_plot<- ggplot() 
  
  for(i in c(1:length(y_values))){
    single_layer<-geom_line(aes_(x=x_values_d,y=y_values[[i]], colour=label_list[[i]]), size=1)
    final_plot<-final_plot+single_layer
  }
  
  for(k in c(1:length(y_value_list))){
    y_values<-y_value_list[[k]]
    
    ec10_yvalue<-y_values[[1]]
    ec50_yvalue<-y_values[[2]]
    ec90_yvalue<-y_values[[3]]
    
    ecs<-ec_list[[k]]
    ec10<-ecs[[1]]
    ec50<-ecs[[2]]
    ec90<-ecs[[3]]
    
    strain<-strains[[k]]
    ec_size<-1.5
    
    if(colour_by_strain==TRUE){
      ec10_layer<-geom_point(aes_(x=ec10,
                                 y=ec10_yvalue,
                                 shape=paste("EC10",strain),
                                 colour=label_list[[k]]),size=ec_size) 
      ec50_layer<-geom_point(aes_(x=ec50,
                                 y=ec50_yvalue,
                                 shape=paste("EC50",strain),
                                 colour=label_list[[k]]),size=ec_size) 
      ec90_layer<-geom_point(aes_(x=ec90,
                                 y=ec90_yvalue,
                                 shape=paste("EC90",strain),
                                 colour=label_list[[k]]),size=ec_size) 
    } else {
      ec10_layer<-geom_point(aes_(x=ec10,
                                 y=ec10_yvalue,
                                 shape=paste("EC10",strain)),size=ec_size) 
      ec50_layer<-geom_point(aes_(x=ec50,
                                 y=ec50_yvalue,
                                 shape=paste("EC50",strain)),size=ec_size) 
      ec90_layer<-geom_point(aes_(x=ec90,
                                 y=ec90_yvalue,
                                 shape=paste("EC90",strain)),size=ec_size) }
      
     # final_plot<-final_plot + ec10_layer + ec50_layer + ec90_layer
  }
  
  
  pretty_plot<-final_plot +
    scale_shape_manual(values = c("EC10 a"=0,
                                    "EC50 a"=1,
                                    "EC90 a"=2,
                                  "EC10 NF"=0,
                                    "EC50 NF"=1,
                                    "EC90 NF"=2,
                                    "EC10 pAct1"=17,
                                    "EC50 pAct1"=16,
                                    "EC90 pAct1"=15)) +
    guides(colour=guide_legend(title = "")) +
    ylab("Slope") +
    scale_colour_manual(values = colour_palette) +
    xlab(xlabel) +
    scale_x_continuous(breaks = doses_experiment,
                    labels = labels_x_axis, 
                    limits = xlim,
                    trans = "log10") +
    ylim(ylims)+
    theme(panel.grid.minor = element_blank(),
            legend.direction = "horizontal", legend.position = "none", 
            panel.border = element_blank(), 
             axis.line = element_line(),
            # axis.text = element_text(size=24),
            # axis.title = element_text(size=24),
            axis.title = element_text(hjust = 1 ),
            panel.background = element_blank()
            ) 
  
  return(pretty_plot)
}

```

```{r spearman plot}
f_spearman_plot<-function(variance_list,control_variances,label_list, control_label_list,plot_doses,span){
  
  final_plot<- ggplot() 
  
  for(i in c(1:length(variance_list))){ #variance list calculated in the facs script.
    single_layer<-
      geom_smooth(aes_(x=plot_doses, y=variances[[i]], colour=label_list[[i]]),se = F, 
                  method = "loess", span=span)  
    final_plot<-final_plot+single_layer
    point_layer<-geom_point(aes_(x=plot_doses, y=variances[[i]], colour=label_list[[i]])) 
    final_plot<-final_plot+point_layer
  }
  
  for(i in c(1:length(control_variances))){
    average<-mean(c(control_variances[[i]][1],control_variances[[i]][24]))
    single_layer<-
      geom_line(aes_(x=c(0,plot_doses), y=average, linetype=control_label_list[i]))
    
    final_plot<-final_plot+single_layer
  }
  
  pretty_plot<-final_plot+
    ylab("Spearman Correlation") +
    scale_colour_manual(values = colour_palette) +
    scale_linetype_manual(values=c("longdash", "dotdash")) +
    xlab(xlabel) +
    scale_x_continuous(breaks = doses_experiment,
                    labels = labels_x_axis, 
                    limits = xlim,
                    trans = "log10") +
    #scale_y_continuous(limits=c(0.60,0.9), breaks = c(0.60,0.65,0.70,0.75,0.80,0.85,0.90)) +
    theme(panel.grid.minor = element_blank(),
            legend.direction = "horizontal", legend.position = "none", 
            panel.border = element_blank(), 
             axis.line = element_line(),
            # axis.text = element_text(size=24),
            # axis.title = element_text(size=24),
            axis.title = element_text(hjust = 1 ),
            panel.background = element_blank()
            ) 
  
}

```

```{r ec values}
f_ec_yvalues<-function(fit_list,ec_list){
  
  all_values<-list()
  
  for(l in c(1:length(ec_list))){
    
    values<-c()
      ec10<-round(ec_list[[l]][1],1)
      ec10_xvalue<-median(which(round(x_values_d,1)==ec10))
      ec10_yvalue<-fit_list[[l]][as.integer(ec10_xvalue)]
      
      ec50<-round(ec_list[[l]][2],1)
      ec50_xvalue<-median(which(round(x_values_d,1)==ec50))
      ec50_yvalue<-fit_list[[l]][as.integer(ec50_xvalue)]
      
      ec90<-round(ec_list[[l]][3],1)
      ec90_xvalue<-median(which(round(x_values_d,1)==ec90))
      ec90_yvalue<-fit_list[[l]][as.integer(ec90_xvalue)]
      
      values<-c(ec10_yvalue,ec50_yvalue,ec90_yvalue)
      all_values[[l]]<-values
  }
  
 
  
  return(all_values)
}
```


```{r overlaid ethanol, glycerol, proline,sd}

descriptives_to_use<-c(1,5,9,13)
control_descriptives_to_use<-c(2,3,4,6,7,8,10,11,12,14,15,16)
xlim<-c(0.15,600)
ylim<-c(0,NA)
dose_control<-c("400","400","200","200","200","200","400","400")

colour_palette<-c("#7a1f1f","#cb3434","#ff3333","#ffcccc")
  #c("pink","firebrick2","tomato3","darkorange1")
  #c("#02085F","#3A05FA","#6E88FC","#91DEFD")
list_of_starting_points<-list(
  c(30000,0.1,30,10,300),
  c(40000,0.1,2,10,300),
  c(80000,0.1,5,10,300),
  c(40000,0.05,5,10,300)
)
# pick which strains/time_points you want to plot, and their labels
frame_list<-descriptives[descriptives_to_use]
label_list_sigmoid<-c("YPeth","SGly","SDpro","SDmin")
label_list_control<-c("ype_norepressor","ype_70",
                      "gly_norepressor","gly_70",
                      "pro_norepressor","pro_70",
                      "sd_norepressor","sd_70")

control_frame_error<-df_list[control_descriptives_to_use]
# pick your controls
control_frame_list<-descriptives[control_descriptives_to_use]



#define x axis doses and the labels for plotting
doses_experiment<-c(0.19,1,5,20,60,200,600)
labels_x_axis<- c("0","1","5","20","60","200","600")


# replace 0 values in the doses with 0.1
for(i in c(1:length(frame_list))){
  frame_list[[i]][1,8]<-0.19
}

# generate log distributed x values for smoother line fitting. 
library(emdbook)
x_values<-lseq(min(frame_list[[1]][,8]),
               max(600),1000)

strain_list<-label_list_sigmoid

# apply the fitting to each frame with its own individual starting points.
sigmoid_fit_parameters<-mapply(function_curve_fitting,frame_list,list_of_starting_points,
                               c(1:length(list_of_starting_points)), 
                                 SIMPLIFY = FALSE)

ec_list<-lapply(sigmoid_fit_parameters,f_ecs)

fit<-lapply(sigmoid_fit_parameters,f_sigmoid_fit,x_values)

sigmoid_plot<-f_plot_sigmoid_curves_overlaid(fit,frame_list, control_frame_list,
                                    label_list_control, xlim, ylim, dose_control)

sigmoid_plot

ggsave(sigmoid_plot+ylab(""),filename =  "overlaid.jpeg", path=output_path, height=6, width=9.04, units = "cm")
ggsave(sigmoid_plot+ylab(""),filename =  "overlaid.pdf", path=output_path, height=6, width=9.04, units = "cm")



#---------------------------------------------------------------------------------------------------
## derivative plot



x_values_d<-seq(0,
               max(frame_list[[1]][,8]),length.out=10000)

sigmoid_d_fit<-lapply(sigmoid_fit_parameters,f_d_sigmoid_fit,x_values_d)

ec_y_values<-f_ec_yvalues(sigmoid_d_fit,ec_list)

ylims<-c(0,10000)

strains<-c("a","a","a","a")

colour_by_strain<-TRUE
f_derivative_plot<-f_plot_sigmoid_d(x_values_d, sigmoid_d_fit, label_list_sigmoid, ylims,ec_y_values,strains)

f_derivative_plot
ggsave(f_derivative_plot+ylab(""),filename =  "overlaid_derivative.jpeg", path=output_path, height=6, width=9.04
       , units = "cm")

ggsave(f_derivative_plot+ylab(""),filename =  "overlaid_derivative.pdf", path=output_path, height=6, width=9.04
       , units = "cm")


#---------------------------------------------------------------------------------------------------
## spearman plot
spearman_dfs<-descriptives_to_use
label_list_spearman<-label_list_sigmoid


spearman_list<-df_with_size[spearman_dfs]

# replace 0 values in the doses with 0.19
for(i in c(1:length(spearman_list))){
  for(k in c(1:nrow(spearman_list[[i]]))){
    if(spearman_list[[i]][k,4]== 0){
      spearman_list[[i]][k,4]<-0.19
    }
  }
}

spearman_doses_list<-list(unique(frame_list[[1]][,8]),unique(frame_list[[2]][,8]),
                     unique(frame_list[[3]][,8]),unique(frame_list[[4]][,8]))

variances<-vector("list",length(spearman_list))

for(k in c(1:length(spearman_list))){
  variance<-vector()
  spearman_doses<-spearman_doses_list[[k]]
  for(i in spearman_doses){
    dataframe<-spearman_list[[k]][which(spearman_list[[k]][,4]==i),]
    var<-cor(dataframe[,3],dataframe[,5], method = "spearman")
    variance<-c(variance,var)
    
  }
  variances[[k]]<-variance
}

spearman<-f_spearman_plot(variances,0,label_list_spearman,"a", spearman_doses, 0.35)
spearman
ggsave(spearman+ylab(""),filename =  "overlaid_spearman.jpeg", path=output_path,height=6, width=9.04, units = "cm")
ggsave(spearman+ylab(""),filename =  "overlaid_spearman.pdf", path=output_path,height=6, width=9.04, units = "cm")




```




```{r}

number<-9
dose<-4
a<-subset(df_with_size[[number]],df_with_size[[number]][,dose]==600)
b<-subset(df_with_size[[number]],df_with_size[[number]][,dose]==150)
c<-subset(df_with_size[[number]],df_with_size[[number]][,dose]==60)
d<-subset(df_with_size[[number]],df_with_size[[number]][,dose]==5)
e<-subset(df_with_size[[number]],df_with_size[[number]][,dose]==0.5)


size<-5
flu<-3
ggplot() +
  geom_point(aes(x=a[,size],y=a[,flu]), colour="red") +
  geom_point(aes(x=b[,size],y=b[,flu]), colour="blue") +
  geom_point(aes(x=c[,size],y=c[,flu]), colour="purple") +
  geom_point(aes(x=d[,size],y=d[,flu]), colour="orange") +
  geom_point(aes(x=e[,size],y=e[,flu])) +
  scale_x_log10()


ggplot() +
  geom_point(aes(x=a[,1],y=a[,2]))

```

