---
title: "R Notebook"
output: html_notebook
---


```{r set parameters}

source("common_functions.R")
source("stat_functions.R")
source("plotting_functions.R")



## colour scale
## colour scale
plot_palette<-c(
"0"="#867236",
"0.5"="#ccccb0",
"1"="#6343c6",
"3"="#addf42",
"5"="#bf4dd6",
"8"="#63d654",
"12"="#d148a3",
"15"="#d7ca3b",
"17"="#6e74cc",
"21"="#5c8f38",
"23"="#77397a",
"25"="#74dc9e",
"30"="#cf466b",
"35"="#76d5d7",
"40"="#de4e34",
"50"="#8cadd1",
"60"="#d6913d",
"75"="#4b5e7d",
"100"="#cad17b",
"150"="#d292c6",
"200"="#435738",
"300"="#98432a",
"400"="#5b957b",
"600"="#7c4a51",

"fry70"="black",
"no repressor"="black",
"tdh3"="blue")



# reading fcs files, t0p1 is the folder for timepoint 0, plate 1 etc.
t0p1_file<-"180411_ffptest/p1"
t1p1_file<-"180411_ffptest/p1/controls"
pattern_read<-"Specimen_001"


output_path<-"C:/Users/aslia/Desktop/pisi/ETH/master project/labbook/plots/april18/180411_ffpcheck" # for saving plots
xlabel<-expression(paste("aTc[ng/mL]", sep = "")) 

starting_well<-1
wells_per_sample<-24

experiment_doses<- c(0,0.5,1,3,5,8,12,15,17,21,23,25,30,35,40,50,60,75,100,150,200,300,400,600)


columns_to_include<-c(2,5,7) #1=FSC-A, #2=FSC-H, #3=FSC-W, #4=SSC-A, #5=SSC-H, #6=SSC-W, #7= 488 [C]-H


strain_names<-c("2759","2674","2739","2661","2683","70") 
time_points<-c("6h")

label_list<- c("7op, TUP1_NF",
               "7op, NF", 
               "7op, NF_TUP1", 
               "no repressor",
               "pTDH3_citrine",
               "fry70"
               )

names(label_list)<-strain_names

#---------------------------------------------------------------------------------------------------------------
## pick the values to subset the data with. 

columns <-c(1:4) #columns to be included in the subset
col_fscw <- 1 #column of FSC-W/H
col_sscw <- 2 #column of SSC-W/H
limit_fscw <-90000 #the value for subsetting based on FSC-W/H
limit_sscw <-90000 #the value for subsetting based on SSC-W/H
lower_limit_fscw <-000 #the value for subsetting based on FSC-W/H, lower limit
lower_limit_sscw <-0000 #the value for subsetting based on SSC-W/H, lower limit

size_subset<-FALSE # set to TRUE if you want to use size_subsetted data, otherwise false.

#---------------------------------------------------------------------------------------------------------------
## descriptive statistics

dose_descriptives<-experiment_doses
cols_descriptives<-3


#---------------------------------------------------------------------------------------------------------------
## smoothed dose response curves of the strains you want

descriptive_sequence<-c(1,2,3) #pick the strains at given timepoints
label_list_smooth<-label_list[c(1,2,3)]
timepoint_used<-1
number_of_timepoints<-1
ncol_legend_smooth<-2
statistic_to_use<-2 #1 is median, 2 is mean
scale_x_breaks_smooth<-experiment_doses
scale_x_labels_smooth<-experiment_doses
legend_title_smooth<-"Strain"
plot_title_smooth<-"Dose Response Curves, 6h"
xlab_smooth<-xlabel
ylab_smooth<-"Fluorescence (a.u.)"
legend_direction_smooth<-"vertical"
legend_position_smooth<-c(0.8,0.2)
additional_arguments_smooth<-NULL
time_point_smooth<-"6h" # to be used in the filename when saving the plot.

height_smooth<-10 # the height and width of the plot to be saved
width_smooth<-15
#---------------------------------------------------------------------------------------------------------------

## size plots
fscw_column_size<-1
sscw_column_size<-2
xlab_size<-"FSC-W"
ylab_size<-"SSC-W"
ylimits_size<-c(40000,NA)
xlimits_size<-c(40000,NA)

labels_for_grid_size<-time_points # labels for the plots in the 2x2 grid

height_size<-10 # saving dimensions
width_size<-15

#---------------------------------------------------------------------------------------------------------------

## histograms
dfs_to_histogram<-c(1,2,3)
doses_histogram<-experiment_doses # the doses you want to plot. if you change this, you should change the manual colour scale inside the function as well. 

labels_histogram<-c("0","0.5","1","3","5","8","12","15","17","21","23","25",
                    "30","35","40","50","60","75","100","150","200","300","400","600",
                    "fry70","tdh3","no repressor") 
breaks_histogram<-labels_histogram

dose_column<-4 #the column with doses 
citrine_column<-3 # column with citrine measurement

control_sequence<-c(3,4,5)
control_labels<-c("fry70","no repressor","tdh3")

size_histogram<- 1.3 # size of the lines
legend_title_histogram<-xlabel
legend_ncol_histogram<-2
legend_position_histogram<-c(0.7,0.8)
xlimits_histogram<-c(0,60000)
ylimits_histogram<-c(0,0.0005)

grid_labels_histograms<-time_points # labels for the plots in the 2x2 grid

height_histograms<-10 # saving dimensions
width_histograms<-15


names_individual_histograms<-c("histogram_TUP1_NF.jpeg","histogram_NF.jpeg","histogram_NF_TUP1.jpeg") # names for saving the plots
x_limits_individual_histogram<-c(0,50000)
x_breaks_individual_histogram<-c(0,9000,25000,50000)
y_breaks_individual_histogram<-c(0,0.0001,0.0002)
y_limits_individual_histogram<-c(0,0.0001)
#---------------------------------------------------------------------------------------------------------------

## descriptive plots
palette<-c("6h"="purple")
colour_labels<-time_points
scale_x_breaks<-experiment_doses
ylab_title<-"Fluorescence (a.u.)"
xlab_title<-xlabel
legend_title<-"Time Point"
stat_columns_1<-c(1,6)
stat_columns_2<-c(2,7)
size_value_descriptives<-4
height_descriptives<-10
width_descriptives<-15

#----------------------------------------------------------------------------------------------------------

## sigmoid fits
descriptives_to_use_sigmoid<-c(1,2,3)
labels_to_use<-c(1,2,3)
colour_palette<-c("red","blue", "orange","green","black", "pink", "purple", "lightblue") # define the colour palette for plotting
# define the plot title, xlabel
plot_title<-"Dose Response Curves, 6h"
xlabel<-expression(paste("aTc[ng/mL]"))

# pick controls for the plot
controls_to_use_sigmoid<-c(4,5,6)
# define starting points for the fitting for each curve: c(a,b,c,d)
# a is the upper asymptote, b is the steepest slope, c is the x axis value at b, e is the lower 
# asymptote. you can define these individually for every curve. 
# d is the symmetry parameter. if =1, the curve is symmetrical around EC50. 
# a negative b gives you an inverse sigmoid, a positive one gives you a sigmoid. or does it? 
list_of_starting_points<-list(
  c(40000,0.8,50,0.2,256),
  c(40000,0.8,50,0.2,2000),
  c(40000,0.8,50,1,256)
)

time_point_sigmoid<-"6h"
height_sigmoid<-10
width_sigmoid<-15

## derivative of sigmoid fit

label_list_derivative<-c("TUP1_NF","NF","NF_TUP1")
#----------------------------------------------------------------------------------------------------------
## size vs. induction plots

palette_density<-plot_palette
x_breaks_density<-labels_histogram
legend_title_density<-xlabel
ncol_legend_density<-2
legend_position_density<-c(0.15,0.68)
size_column<-5
citrine_column<-3
dose_column<-4

doses_size_vs_induction<-experiment_doses # the doses you want to plot. if you change this, you should change the manual colour scale inside the function as well. 

labels_size_vs_induction<-labels_histogram  #labels that will appear on the legend, and that determine the colour_scale_manual mappings. If you change anything here, change it in the colour scale inside the function as well. 

grid_labels_density<-time_points

height_density<-10
width_density<-15

#----------------------------------------------------------------------------------------------------------
## calculating the spearman correlation between size and fluorescence.

spearman_dfs<-c(1:6)
label_list_spearman<-label_list[c(1:6)]
#----------------------------------------------------------------------------------------------------------## QQPLOTS
# in the dataframelist1/2, pick the strain you want to plot. in the doses part, you can specify which 
# dose is to be plotted. in columns, pick which column is to be plotted. dataframelist1 and 2 will be paired in each qqplot (i.e. dataframelist1[1] is plotted against dataframelist2[[1]])
dataframelist1<-c(1,1,1)
dataframelist1_doses<-c(0,200,400)
dataframelist1_columns<-c(3,3,3)
dataframelist2<-c(2,2,2)
dataframelist2_doses<-c(0,200,400)
dataframelist2_columns<-c(3,3,3)

xlims_qqplot<-list(c(0,NA),c(0,NA),c(0,NA))
ylims_qqplot<-list(c(0,NA),c(0,NA),c(0,NA))

titles_qqplot<-c("NF vs pAct1,0atc",
          "NF vs pAct1,200atc",
          "NF vs pAct1,400atc"
          )

width_qq<-15
height_qq<-10

```


```{r}
source("facs_script.R")


ggplot() +
  geom_density(aes(x=df_list[[4]][which(df_list[[4]][,4]==0),3], colour="no repressor"), size=1) +
  geom_density(aes(x=df_list[[5]][which(df_list[[5]][,4]==0),3], colour="pTDH3"), size=1)  +
  theme_bw()



```




