---
title: "R Notebook"
output: html_notebook
---

```{r}


library(ggplot2)
source("common_functions.R")
source("stat_functions.R")

t0p1_file<-"180910_2776_release/measure"
t0p2_file<-"180910_2776_release/atc_control"
t0p3_file<-"180910_2776_release/parent_control"


output_path<-"C:/Users/aslia/Desktop/pisi/ETH/master project/labbook/plots/sep18/180910_arrest&release" # for saving plots
pattern_read<-""

starting_well<-1

time_points<-c("t0","t90","t180","t270","t300","r5","r10","r15","r20","r25","r30","r35","r40",
               "r45","r50","r55","r60","r65","r70","r75","r80","r85","r90","r95","r100","r105","r120")


columns_to_include<-c(3,6,7) #1=FSC-A, #2=FSC-H, #3=FSC-W, #4=SSC-A, #5=SSC-H, #6=SSC-W, #7= 488 [C]-H


label_list<- c("2776_0_t0",
               "2776_0_t90",
               "2776_0_t180",
               "2776_0_t270",
               "2776_0_t300",
               
               "2776_0_r5",
               "2776_0_r10",
               "2776_0_r15",
               "2776_0_r20",
               "2776_0_r25",
               "2776_0_r30",
               "2776_0_r35",
               "2776_0_r40",
               "2776_0_r45",
               "2776_0_r50",
               "2776_0_r55",
               "2776_0_r60",
               "2776_0_r65",
               "2776_0_r70",
               "2776_0_r75",
               "2776_0_r80",
               "2776_0_r85",
               "2776_0_r90",
               "2776_0_r95",
               "2776_0_r100",
               "2776_0_r105",
               "2776_0_r120",
               
               "2776_100_t300",
               "2776_100_r60",
               "2776_100_r120",
  
  
               "parent_t0",
               "parent_t300",
               "parent_r60",
               "parent_r120"
               )


#---------------------------------------------------------------------------------------------------------------
## pick the values to subset the data with. 

columns <-c(1:4) #columns to be included in the subset
col_fscw <- 1 #column of FSC-W/H
col_sscw <- 2 #column of SSC-W/H
limit_fscw <-90000 #the value for subsetting based on FSC-W/H
limit_sscw <-90000 #the value for subsetting based on SSC-W/H
lower_limit_fscw <-000 #the value for subsetting based on FSC-W/H, lower limit
lower_limit_sscw <-0000 #the value for subsetting based on SSC-W/H, lower limit

size_subset<-FALSE # set to TRUE if you want to use size_subsetted data, otherwise false.

#---------------------------------------------------------------------------------------------------------------



```


```{r}


f_time_lapse_plot<-function(dataframe, title, ylims, xlims){
  
  final_plot<- ggplot(dataframe) +
    geom_histogram(aes_(x=dataframe[,3]), binwidth = 100) +
    facet_wrap(~dataframe[,4]) +
    
    theme_bw() +
    ggtitle(title) +
    xlab("Fluorescence (a.u.)") +
    scale_x_continuous(limits=(xlims))+
    ylim(ylims)
  
  return(final_plot)
  
}

ylims<-c(0,160)
xlims<-c(0,50000)

titles<-list("cdc20, arrest&release","cdc20, 100 aTc", "parent strain")
time_lapse_plots<-mapply(f_time_lapse_plot, df_list, titles, MoreArgs = list(ylims, xlims), SIMPLIFY = F)

time_lapse_plots[[1]]

 mapply(f_save,time_lapse_plots,names(df_list),
         MoreArgs = list(output_path, "", 10, 15), SIMPLIFY = F)





```

```{r}
f_ssc_vs_fsc_plot<-
  function(dataframe, title){
  
  final_plot<- ggplot(dataframe) +
    geom_bin2d(aes_(x=dataframe[,1], y=dataframe[,3]), bins=100) +
    facet_wrap(~dataframe[,4]) +
    
    theme_bw() +
    ggtitle(title) +
    xlab("FSC-W") +
    ylab("stain") +
    xlim(50000,100000)+
    ylim(0000,100000)
  # +
  #   scale_x_continuous(limits=(xlims))+
  #   ylim(ylims)
  
  return(final_plot)
  
}
size_plots<-mapply(f_ssc_vs_fsc_plot, df_list, titles, SIMPLIFY = F)

size_plots[[9]]

mapply(f_save,size_plots,names(df_list),
         MoreArgs = list(paste(output_path, "/size",sep=""), "", 10, 15), SIMPLIFY = F)


```


```{r}

ggplot(df_list[[1]]) +
  geom_density2d(aes(x=df_list[[1]][,1], y=df_list[[1]][,3])) +
  facet_wrap(~df_list[[1]][,4])


ggplot(df_list[[2]]) +
  geom_density2d(aes(x=df_list[[2]][,1], y=df_list[[2]][,3])) +
  facet_wrap(~df_list[[2]][,4])



n<-2
ggplot(df_with_size[[n]]) +
  geom_density_2d(aes(df_with_size[[n]][,5], df_with_size[[n]][,3])) +
  facet_wrap(~df_with_size[[n]][,4])


```

