---------
title: "R Notebook"
output: html_notebook
---



```{r}
source("common_functions.R")
source("stat_functions.R")
source("plotting_functions.R")

t0p1_file<-"figure1/ethanol (24h)/" #180405
t1p1_file<-"figure1/glycerol(24h)/"
t2p1_file<-"figure1/proline (24h)/" #180313
t6p1_file<-"figure1/sd (6h)/" # 180327
t8p1_file<-"figure1/180419_2opypd/6h" # 180327
t3p1_file<-"figure1/ethanol (24h)/controls" #180405
t4p1_file<-"figure1/glycerol(24h)/controls"
t5p1_file<-"figure1/proline (24h)/controls"  #180313
t7p1_file<-"figure1/sd (6h)/controls" # 180327
t9p1_file<-"figure1/180419_2opypd/6h/controls" # 180327
pattern_read<-"Specimen_001"


output_path<-"C:/Users/aslia/Desktop/pisi/ETH/master project/labbook/paper/figures/figure1"
# create folders named size, svf, histograms, boxplots under this directory. 

starting_well<-1
wells_per_sample<-24


ypethanol_doses<-c(0,0.2,1,2,3,4,5,6,8,10,13,15,17,20,26,30,35,45,50,65,80,100,200,400)
glycerol_doses<-c(0,0.5,1,2,3,4,5,7,8,9,10,12,14,16,18,20,23,25,27,30,45,60,100,200)
proline_doses<-c(0,0.2,0.5,0.7,1,1.5,2,2.5,3,4,5,6,7,8,10,12,15,20,25,30,40,45,60,200)
sd_doses<- c(0,0.2,1,3,4,5,7,10,13,17,23,30,40,50,70,100,130,150,180,200,250,300,350,400)
ypd_doses<- c(0,0.5,1,3,5,8,12,15,17,21,23,25,30,35,40,50,60,75,100,150,200,300,400,600)
ypd_doses_desc<-c(0,0.5,1,3,5,8,12,15,17,21,23,25,30,35,40,50,60,75,100,150,200,300,400,600)
experiment_doses<-list(ypethanol_doses,ypethanol_doses,c(0,400),c(0,400),c(0,400),
                       glycerol_doses, glycerol_doses,c(0,200),c(0,200),c(0,200),
                       proline_doses, proline_doses,c(0,200),c(0,200),c(0,200),
                       sd_doses,sd_doses,c(0,400),c(0,400),c(0,400),
                       ypd_doses,ypd_doses,c(0,600),c(0,600),c(0,600))

experiment_doses_desc<-list(ypethanol_doses,ypethanol_doses,c(0,400),c(0,400),c(0,400),
                       glycerol_doses, glycerol_doses,c(0,200),c(0,200),c(0,200),
                       proline_doses, proline_doses,c(0,200),c(0,200),c(0,200),
                       sd_doses,sd_doses,c(0,400),c(0,400),c(0,400),
                       ypd_doses_desc,ypd_doses_desc,c(0,600),c(0,600),c(0,600))

columns_to_include<-c(3,6,7) #1=FSC-A, #2=FSC-H, #3=FSC-W, #4=SSC-A, #5=SSC-H, #6=SSC-W, #7= 488 [C]-H

strain_names<-c("2561eth","2562eth","2551eth","2683eth","70eth",
                "2561gly","2562gly","2551gly","2683gly","70gly",
                "2561pro","2562pro","2551pro","2683pro","70pro",
                "2561sd","2562sd","2551sd","2683sd","70sd",
                "2561ypd","2562ypd","2551ypd","2683ypd","70ypd"
                ) 
time_points<-c("24h")

label_list<- c("2op NF_eth",
               "2op pAct1_eth",
               "fry70_eth",
               "no repressor_eth",
               "tdh3_eth",
               "2op NF_gly",
               "2op pAct1_gly",
               "fry70_gly",
               "no repressor_gly",
               "tdh3_gly",
               "2op NF_pro",
               "2op pAct1_pro",
               "no repressor_pro",
               "tdh3_pro",
               "fry70_pro",
               "2op NF_sd",
               "2op pAct1_sd",
               "no repressor_sd",
               "tdh3_sd",
               "fry70_sd",
               "2op NF_ypd",
               "2op pAct1_ypd",
               "no repressor_ypd",
               "tdh3_ypd",
               "fry70_ypd"
               )

names(label_list)<-strain_names

xlabel<-"aTc [ng/mL]"

#---------------------------------------------------------------------------------------------------------------
## pick the values to subset the data with. 

columns <-c(1:4) #columns to be included in the subset
col_fscw <- 1 #column of FSC-W/H
col_sscw <- 2 #column of SSC-W/H
limit_fscw <-72000 #the value for subsetting based on FSC-W/H
limit_sscw <-100000 #the value for subsetting based on SSC-W/H
lower_limit_fscw <-68000 #the value for subsetting based on FSC-W/H, lower limit
lower_limit_sscw <-40000 #the value for subsetting based on SSC-W/H, lower limit

size_subset<-FALSE # set to TRUE if you want to use size_subsetted data, otherwise false.

#----------------------------------------------------------------------------------------------------------
## descriptive statistics

dose_descriptives<-experiment_doses
cols_descriptives<-3



```

```{r plotting function}
# creating the individual plots
library("minpack.lm")
library("ggthemes")
## plotting the sigmoid curves.
xlabel<-expression(paste("aTc[ng/mL]"))

f_plot_sigmoid_curves_single<-
  # plot the fitted line and the individual data points. 
  function(fit_list,frame_list, control_frame_list,dose_control,label_list_control, xlim, ylim,
           ec_list,strain_list,doses){
    formatter<-function(x){x/1000}
    final_plot<-ggplot() 
    # plot the lines
    for (i in c(1:length(fit_list))){
      print(i)
      single_layer_line<- geom_line(aes_(x=x_values, y=fit_list[[i]],
                                         colour=label_list_sigmoid[[i]]), size=1)
      final_plot<-final_plot+single_layer_line
    }
    
    # plot the individual data points
    for (j in c(1:length(frame_list))){
      single_layer_point<- geom_point(aes_(x=frame_list[[j]][,8],y=frame_list[[j]][,1],
                                           colour=label_list_sigmoid[[j]]))   
      final_plot<-final_plot+single_layer_point
    }
    
   
    # plot the controls
    
    for(k in c(1:length(control_frame_list))){
      frame<-control_frame_list[[k]][which(control_frame_list[[k]][,8]==dose_control),]

      single_layer_control<- geom_hline(aes_(yintercept=frame[,1],
                                             linetype=label_list_control[[k]]), colour="black")
      ribbon_layer_control<- geom_ribbon(aes_(ymin=frame[,1]-(frame[,6]*frame[,1]),
                                              ymax=frame[,1]-(frame[,6]*frame[,1]),
                                              x=x_values))

      final_plot<-final_plot+single_layer_control

    }
    
    ## find the ECs
    
     for(l in c(1:length(ec_list))){
      ec10<-round(ec_list[[l]][1],1)
      ec10_xvalue<-median(which(round(x_values,1)==ec10))
      ec10_yvalue<-fit_list[[l]][as.integer(ec10_xvalue)]
      
      ec50<-round(ec_list[[l]][2],0)
      ec50_xvalue<-median(which(round(x_values,0)==ec50))
      ec50_yvalue<-fit_list[[l]][as.integer(ec50_xvalue)]
      
      ec90<-round(ec_list[[l]][3],0)
      ec90_xvalue<-median(which(round(x_values,0)==ec90))
      ec90_yvalue<-fit_list[[l]][as.integer(ec90_xvalue)]
      print(which(round(x_values,0)==ec90))
      print(ec90_xvalue)
      print(ec90_yvalue)
      
      strain<-strain_list[[l]]
      ec_size<-1.5
      ec10_layer<-geom_point(aes_(x=ec10,
                                 y=ec10_yvalue,
                                 shape=paste("EC10",strain)),size=ec_size) 
      ec50_layer<-geom_point(aes_(x=ec50,
                                 y=ec50_yvalue,
                                 shape=paste("EC50",strain)),size=ec_size) 
      ec90_layer<-geom_point(aes_(x=ec90,
                                 y=ec90_yvalue,
                                 shape=paste("EC90",strain)),size=ec_size) 
      
      #final_plot<-final_plot + ec10_layer + ec50_layer + ec90_layer
      
    }
    
    pretty_plot<-final_plot +
      scale_linetype_manual(values=c("longdash","dotted", "dotdash")) +
      scale_shape_manual(values = c("EC10 NF"=0,
                                    "EC50 NF"=1,
                                    "EC90 NF"=2,
                                    "EC10 pAct1"=17,
                                    "EC50 pAct1"=16,
                                    "EC90 pAct1"=15)) +
      scale_colour_manual(values = colour_palette) +
      scale_x_continuous(breaks = doses_experiment,
                    labels = labels_x_axis, 
                    limits = xlim,
                    trans = "log10") +
      scale_y_continuous(limits = ylim, labels=formatter) +
      guides(colour=guide_legend(title = "Strains",nrow=2)) +
      # ggtitle(plot_title) +
      xlab(xlabel) +
      ylab(expression(paste("Fluorescence x","10"^"3","(a.u.)",sep=""))) +
      theme(panel.grid.minor = element_blank(),
            legend.direction = "horizontal", legend.position = "none", 
            panel.border = element_blank(), 
             axis.line = element_line(),
            # axis.text = element_text(size=24),
            # axis.title = element_text(size=24),
            axis.title = element_text(hjust = 1),
            panel.background = element_blank()
            ) 
    
      # geom_rangeframe(aes(x=c(min(x_values):max(x_values)), 
      #                     y=seq(0,50,length.out=length(c(min(x_values):max(x_values))))),sides = "lb") 
    
    return(pretty_plot)
  }

```

```{r}
f_ec_yvalues<-function(fit_list,ec_list){
  
  all_values<-list()
  
  for(l in c(1:length(ec_list))){
    
    values<-c()
      ec10<-round(ec_list[[l]][1],1)
      ec10_xvalue<-median(which(round(x_values_d,1)==ec10))
      ec10_yvalue<-fit_list[[l]][as.integer(ec10_xvalue)]
      
      ec50<-round(ec_list[[l]][2],1)
      ec50_xvalue<-median(which(round(x_values_d,1)==ec50))
      ec50_yvalue<-fit_list[[l]][as.integer(ec50_xvalue)]
      
      ec90<-round(ec_list[[l]][3],1)
      ec90_xvalue<-median(which(round(x_values_d,1)==ec90))
      ec90_yvalue<-fit_list[[l]][as.integer(ec90_xvalue)]
      
      values<-c(ec10_yvalue,ec50_yvalue,ec90_yvalue)
      all_values[[l]]<-values
  }
  
 
  
  return(all_values)
}
```


```{r derivative plotting function}
f_fit_function<-function(x) (e + (a-e)/((1 + ((((x/c)^b))^(d)))))
d_fit_function<-D(body(f_fit_function),'x')

f_d_sigmoid <- function(params, x) {
  -((params[1] - params[5]) * ((1 + ((x/params[3])^params[2]))^((params[4]) - 1) * 
                                 ((params[4]) * ((x/params[3])^(params[2] - 1) * 
                                                   (params[2] * (1/params[3])))))/((1 +
                                                                                      ((x/params[3])^params[2]))^
                                                                                     (params[4]))^2)
}


f_d_sigmoid_fit<-function(params,x_values_d){    
  sigmoid_fit <- f_d_sigmoid(params,x_values_d)
  return(sigmoid_fit)
}

f_plot_sigmoid_d<-function(x_values_d, y_values, label_list,ylims,y_value_list,strains){
  
  final_plot<- ggplot() 
  
  for(i in c(1:length(y_values))){
    single_layer<-geom_line(aes_(x=x_values_d,y=y_values[[i]], colour=label_list[[i]]), size=1)
    final_plot<-final_plot+single_layer
  }
  
  for(k in c(1:length(y_value_list))){
    y_values<-y_value_list[[k]]
    
    ec10_yvalue<-y_values[[1]]
    ec50_yvalue<-y_values[[2]]
    ec90_yvalue<-y_values[[3]]
    
    ecs<-ec_list[[k]]
    ec10<-ecs[[1]]
    ec50<-ecs[[2]]
    ec90<-ecs[[3]]
    
    strain<-strains[[k]]
    ec_size<-1.5
    
    if(colour_by_strain==TRUE){
      ec10_layer<-geom_point(aes_(x=ec10,
                                 y=ec10_yvalue,
                                 shape=paste("EC10",strain),
                                 colour=label_list[[k]]),size=ec_size) 
      ec50_layer<-geom_point(aes_(x=ec50,
                                 y=ec50_yvalue,
                                 shape=paste("EC50",strain),
                                 colour=label_list[[k]]),size=ec_size) 
      ec90_layer<-geom_point(aes_(x=ec90,
                                 y=ec90_yvalue,
                                 shape=paste("EC90",strain),
                                 colour=label_list[[k]]),size=ec_size) 
    } else {
      ec10_layer<-geom_point(aes_(x=ec10,
                                 y=ec10_yvalue,
                                 shape=paste("EC10",strain)),size=ec_size) 
      ec50_layer<-geom_point(aes_(x=ec50,
                                 y=ec50_yvalue,
                                 shape=paste("EC50",strain)),size=ec_size) 
      ec90_layer<-geom_point(aes_(x=ec90,
                                 y=ec90_yvalue,
                                 shape=paste("EC90",strain)),size=ec_size) }
      
     # final_plot<-final_plot + ec10_layer + ec50_layer + ec90_layer
  }
  
  
  pretty_plot<-final_plot +
    scale_shape_manual(values = c("EC10 a"=0,
                                    "EC50 a"=1,
                                    "EC90 a"=2,
                                  "EC10 NF"=0,
                                    "EC50 NF"=1,
                                    "EC90 NF"=2,
                                    "EC10 pAct1"=17,
                                    "EC50 pAct1"=16,
                                    "EC90 pAct1"=15)) +
    guides(colour=guide_legend(title = "Strain")) +
    ylab("Slope") +
    scale_colour_manual(values = colour_palette) +
    xlab(xlabel) +
    scale_x_continuous(breaks = doses_experiment,
                    labels = labels_x_axis, 
                    limits = xlim,
                    trans = "log10") +
    ylim(ylims)+
    theme(panel.grid.minor = element_blank(),
            legend.direction = "horizontal", legend.position = "none", 
            panel.border = element_blank(), 
             axis.line = element_line(),
            # axis.text = element_text(size=24),
            # axis.title = element_text(size=24),
            axis.title = element_text(hjust = 1 ),
            panel.background = element_blank()
            ) 
  
  return(pretty_plot)
}

```

```{r spearman plot}
f_spearman_plot<-function(variance_list,label_list, plot_doses,span){
  
  final_plot<- ggplot() 
  
  for(i in c(1:length(variance_list))){ #variance list calculated in the facs script.
    single_layer<-
      geom_smooth(aes_(x=plot_doses, y=variances[[i]], colour=label_list[[i]]),se = F, 
                  method = "loess", span=span)  
    final_plot<-final_plot+single_layer
    point_layer<-geom_point(aes_(x=plot_doses, y=variances[[i]], colour=label_list[[i]])) 
    final_plot<-final_plot+point_layer
  }
  
  pretty_plot<-final_plot+
    ylab("Spearman Correlation") +
    scale_colour_manual(values = colour_palette) +
    xlab(xlabel) +
    scale_x_continuous(breaks = doses_experiment,
                    labels = labels_x_axis, 
                    limits = xlim,
                    trans = "log10") +
    theme(panel.grid.minor = element_blank(),
            legend.direction = "horizontal", legend.position = "none", 
            panel.border = element_blank(), 
             axis.line = element_line(),
            # axis.text = element_text(size=24),
            # axis.title = element_text(size=24),
            axis.title = element_text(hjust = 1 ),
            panel.background = element_blank()
            ) 
  
}

```




```{r ethanol}
# for ethanol I had to lower the higher controls manually, and then add a break to the y axis in illustrator. 

# creating the individual plots
library("minpack.lm")
## plotting the sigmoid curves.


descriptives_to_use<-c(1,2)
control_descriptives_to_use<-c(3,4,5)
labels_to_use<-c(1,2)
dose_control<-"400"
xlim<-c(0.1,450)
ylim<-c(0,NA)

colour_palette<-c("darkred","lightblue")
list_of_starting_points<-list(
  c(30000,0.8,20,1,5000),
  c(30000,0.8,20,1,3000)
  # c(7000,0.1,2,5000),
  # c(7000,0.1,2,3000),
  # c(10000,0.3,6,3000),
  # c(10000,0.5,2,5000)
)
# pick which strains/time_points you want to plot, and their labels
frame_list<-descriptives[descriptives_to_use]
label_list_sigmoid<-label_list[labels_to_use]
label_list_control<-label_list[control_descriptives_to_use]

control_frame_error<-df_list[control_descriptives_to_use]
# pick your controls
control_frame_list<-descriptives[control_descriptives_to_use]


#define x axis doses and the labels for plotting
doses_experiment<-c(0.1,0.2,1,3,5,10,20,30,50,100,400)
labels_x_axis<-c("0","0.2","1","3","5","10","20","30","50","100","400")


# replace 0 values in the doses with 0.1
for(i in c(1:length(frame_list))){
  frame_list[[i]][1,8]<-0.1
}


# generate log distributed x values for smoother line fitting. 
library(emdbook)
x_values<-lseq(min(frame_list[[1]][,8]),
               max(frame_list[[1]][,8]),1000)


# apply the fitting to each frame with its own individual starting points.
sigmoid_fit_parameters<-mapply(function_curve_fitting,frame_list,list_of_starting_points, 
                                 SIMPLIFY = FALSE)

ec_list<-lapply(sigmoid_fit_parameters,f_ecs)

fit<-lapply(sigmoid_fit_parameters,f_sigmoid_fit,x_values)

sigmoid_plot<-f_plot_sigmoid_curves_single(fit,frame_list, control_frame_list,
                                    dose_control, label_list_control, xlim, ylim,ec_list,strain_list)

sigmoid_plot

#ggsave(sigmoid_plot,filename =  "ethanol.jpeg", path=output_path, height=10, width=15, units="cm")
```


```{r glycerol}
# creating the individual plots
library("minpack.lm")
## plotting the sigmoid curves.



descriptives_to_use<-c(6,7)
control_descriptives_to_use<-c(8,9,10)
labels_to_use<-c(6,7)
dose_control<-"0"
xlim<-c(0.3,NA)
ylim<-c(0,NA)

colour_palette<-c("darkred","lightblue")
list_of_starting_points<-list(
  c(7000,0.1,2,1,5000),
  c(7000,0.1,2,1,3000)
  # c(7000,0.1,2,5000),
  # c(7000,0.1,2,3000),
  # c(10000,0.3,6,3000),
  # c(10000,0.5,2,5000)
)
# pick which strains/time_points you want to plot, and their labels
frame_list<-descriptives[descriptives_to_use]
label_list_sigmoid<-label_list[labels_to_use]
label_list_control<-label_list[control_descriptives_to_use]

control_frame_error<-df_list[control_descriptives_to_use]
# pick your controls
control_frame_list<-descriptives[control_descriptives_to_use]
for(i in c(2,3)){
  control_frame_list[[i]][,1]<-control_frame_list[[i]][,1]
}


#define x axis doses and the labels for plotting
doses_experiment<-c(0.3,0.5,1,3,5,10,20,30,60,200)
labels_x_axis<-c("0","0.5","1","3","5","10","20","30", "60","200")


# replace 0 values in the doses with 0.1
for(i in c(1:length(frame_list))){
  frame_list[[i]][1,8]<-0.3
}


# generate log distributed x values for smoother line fitting. 
library(emdbook)
x_values<-lseq(min(frame_list[[1]][,8]),
               max(frame_list[[1]][,8]),1000)


strain_list<-c("NF","pAct1")

# apply the fitting to each frame with its own individual starting points.
sigmoid_fit_parameters<-mapply(function_curve_fitting,frame_list,list_of_starting_points, 
                                 SIMPLIFY = FALSE)

ec_list<-lapply(sigmoid_fit_parameters,f_ecs)

fit<-lapply(sigmoid_fit_parameters,f_sigmoid_fit,x_values)

sigmoid_plot<-f_plot_sigmoid_curves_single(fit,frame_list, control_frame_list,
                                    dose_control, label_list_control, xlim, ylim,ec_list,strain_list)
sigmoid_plot

#ggsave(sigmoid_plot,filename =  "glycerol.jpeg", path=output_path, height=10, width=15)
```

```{r proline}
# for proline I removed the dose 0 since we have a strange autofluorescence lowering effect of aTc. For the same reason I used controls that have 200ng/mL aTc on them and not the 0 versions like the others. 



descriptives_to_use<-c(11,12)
control_descriptives_to_use<-c(13,14,15)
labels_to_use<-c(11,12)
dose_control<-"200"
xlim<-c(0.1,200)
ylim<-c(0,NA)

colour_palette<-c("darkred","lightblue","grey20","grey50","grey80")
list_of_starting_points<-list(
  c(40000,0.5,5,1,5000),
  c(40000,0.8,1,10,5000)
  # c(7000,0.1,2,5000),
  # c(7000,0.1,2,3000),
  # c(10000,0.3,6,3000),
  # c(10000,0.5,2,5000)
)
# pick which strains/time_points you want to plot, and their labels
frame_list<-descriptives[descriptives_to_use]
label_list_sigmoid<-label_list[labels_to_use]
label_list_control<-label_list[control_descriptives_to_use]

control_frame_error<-df_list[control_descriptives_to_use]
# pick your controls
control_frame_list<-descriptives[control_descriptives_to_use]
for(i in c(2,3)){
  control_frame_list[[i]][,1]<-control_frame_list[[i]][,1]
}


#define x axis doses and the labels for plotting
doses_experiment<-c(0.1,0.5,1,2,3,5,10,20,30,60,200)
labels_x_axis<- c("0","0.5","1","2","3","5","10","20","30","60","200")


# replace 0 values in the doses with 0.1
for(i in c(1:length(frame_list))){
  frame_list[[i]][1,8]<-0.1
}

# generate log distributed x values for smoother line fitting. 
library(emdbook)
x_values<-lseq(min(frame_list[[1]][,8]),
               max(frame_list[[1]][,8]),1000)

strain_list<-c("NF","pAct1")

# apply the fitting to each frame with its own individual starting points.
sigmoid_fit_parameters<-mapply(function_curve_fitting,frame_list,list_of_starting_points, 
                                 SIMPLIFY = FALSE)

ec_list<-lapply(sigmoid_fit_parameters,f_ecs)

fit<-lapply(sigmoid_fit_parameters,f_sigmoid_fit,x_values)

sigmoid_plot<-f_plot_sigmoid_curves_single(fit,frame_list, control_frame_list,
                                    dose_control, label_list_control, xlim, ylim,ec_list,strain_list)

sigmoid_plot

#ggsave(sigmoid_plot,filename =  "proline.jpeg", path=output_path, height=10, width=15, units = "cm")
```


```{r sd}
descriptives_to_use<-c(16,17)
control_descriptives_to_use<-c(18,19,20)
labels_to_use<-c(16,17)
dose_control<-"400"
xlim<-c(0.1,200)
ylim<-c(0,NA)

colour_palette<-c("darkred","lightblue","grey20","grey50","grey80")
list_of_starting_points<-list(
  c(40000,0.5,2,1,5000),
  c(40000,0.3,3,1,5000)
  # c(7000,0.1,2,5000),
  # c(7000,0.1,2,3000),
  # c(10000,0.3,6,3000),
  # c(10000,0.5,2,5000)
)
# pick which strains/time_points you want to plot, and their labels
frame_list<-descriptives[descriptives_to_use]
label_list_sigmoid<-label_list[labels_to_use]
label_list_control<-label_list[control_descriptives_to_use]

control_frame_error<-df_list[control_descriptives_to_use]
# pick your controls
control_frame_list<-descriptives[control_descriptives_to_use]
for(i in c(2,3)){
  control_frame_list[[i]][,1]<-control_frame_list[[i]][,1]
}

#doses sd: c(0,0.2,1,3,4,5,7,10,13,17,23,30,40,50,70,100,130,150,180,200,250,300,350,400)
c(0,0.2,1,3,4,5,7,10,13,17,23,30,40,50,70,100,130,150,180,200,250,300,350,400)
#define x axis doses and the labels for plotting
doses_experiment<-c(0.1,1,3,5,10,20,30,70,100,200)
labels_x_axis<- c("0","1","3","5","10","20","30","70","100","200")


# replace 0 values in the doses with 0.1
for(i in c(1:length(frame_list))){
  frame_list[[i]][1,8]<-0.1
}

# generate log distributed x values for smoother line fitting. 
library(emdbook)
x_values<-lseq(min(frame_list[[1]][,8]),
               max(frame_list[[1]][,8]),1000)

strain_list<-c("NF","pAct1")

# apply the fitting to each frame with its own individual starting points.
sigmoid_fit_parameters<-mapply(function_curve_fitting,frame_list,list_of_starting_points, 
                                 SIMPLIFY = FALSE)

ec_list<-lapply(sigmoid_fit_parameters,f_ecs)

fit<-lapply(sigmoid_fit_parameters,f_sigmoid_fit,x_values)

sigmoid_plot<-f_plot_sigmoid_curves_single(fit,frame_list, control_frame_list,
                                    dose_control, label_list_control, xlim, ylim,ec_list,strain_list)

sigmoid_plot

#ggsave(sigmoid_plot,filename =  "sd.jpeg", path=output_path, height=10, width=15, units = "cm")

```


```{r ypd}
descriptives_to_use<-c(21,22)
control_descriptives_to_use<-c(23,24,25)
labels_to_use<-c(21,22)
dose_control<-"600"
xlim<-c(0.1,600)
ylim<-c(0,NA)

colour_palette<-c("darkred","lightblue","grey20","grey50","grey80")
list_of_starting_points<-list(
  c(40000,-1,20,1,5000),
  c(40000,-2,15,1,5000)
  # c(7000,0.1,2,5000),
  # c(7000,0.1,2,3000),
  # c(10000,0.3,6,3000),
  # c(10000,0.5,2,5000)
)
# pick which strains/time_points you want to plot, and their labels
frame_list<-descriptives[descriptives_to_use]
label_list_sigmoid<-label_list[labels_to_use]
label_list_control<-label_list[control_descriptives_to_use]

control_frame_error<-df_list[control_descriptives_to_use]
# pick your controls
 control_frame_list<-descriptives[control_descriptives_to_use]
# for(i in c(2,3)){
#   control_frame_list[[i]][,1]<-control_frame_list[[i]][,1]
# }



#define x axis doses and the labels for plotting
doses_experiment<-c(0.1,1,3,5,12,30,60,100,300,600)
labels_x_axis<- c("0","1","3","5","12","30","60","100","300","600")


# replace 0 values in the doses with 0.1
for(i in c(1:length(frame_list))){
  frame_list[[i]][1,8]<-0.1
}

# generate log distributed x values for smoother line fitting. 
library(emdbook)
x_values<-lseq(min(frame_list[[1]][,8]),
               max(frame_list[[1]][,8]),1000)

strain_list<-c("NF","pAct1")

# apply the fitting to each frame with its own individual starting points.
sigmoid_fit_parameters<-mapply(function_curve_fitting,frame_list,list_of_starting_points, 
                                 SIMPLIFY = FALSE)

ec_list<-lapply(sigmoid_fit_parameters,f_ecs)

fit<-lapply(sigmoid_fit_parameters,f_sigmoid_fit,x_values)

sigmoid_plot<-f_plot_sigmoid_curves_single(fit,frame_list, control_frame_list,
                                    dose_control, label_list_control, xlim, ylim,ec_list,strain_list)

sigmoid_plot

ggsave(sigmoid_plot,filename =  "ypd.jpeg", path=output_path, height=6.3, width=9.5, units = "cm")

#---------------------------------------------------------------------------------------------------
## derivative plot

x_values_d<-seq(0,
               max(frame_list[[1]][,8]),length.out=10000)

sigmoid_d_fit<-lapply(sigmoid_fit_parameters,f_d_sigmoid_fit,x_values_d)

ec_y_values<-f_ec_yvalues(sigmoid_d_fit,ec_list)

ylims<-c(0,NA)

colour_by_strain<-FALSE

f_derivative_plot<-f_plot_sigmoid_d(x_values_d, sigmoid_d_fit, label_list_sigmoid, ylims, ec_y_values,
                                    strain_list)

f_derivative_plot
ggsave(f_derivative_plot,filename =  "ypd_derivative.jpeg", path=output_path, height=6.3, width=9.5, units = "cm")



#---------------------------------------------------------------------------------------------------
## spearman plot
spearman_dfs<-descriptives_to_use
label_list_spearman<-label_list_sigmoid


spearman_list<-df_with_size[spearman_dfs]

# replace 0 values in the doses with 0.1
for(i in c(1:length(spearman_list))){
  for(k in c(1:nrow(spearman_list[[i]]))){
    if(spearman_list[[i]][k,4]== 0){
      spearman_list[[i]][k,4]<-0.1
    }
  }
}

spearman_doses<-unique(frame_list[[1]][,8])

variances<-vector("list",length(spearman_list))

for(k in c(1:length(spearman_list))){
  variance<-vector()
  for(i in spearman_doses){
    dataframe<-spearman_list[[k]][which(spearman_list[[k]][,4]==i),]
    var<-cor(dataframe[,3],dataframe[,5], method = "spearman")
    variance<-c(variance,var)
    
  }
  variances[[k]]<-variance
}

spearman<-f_spearman_plot(variances,label_list_spearman, spearman_doses, 0.35)
spearman
ggsave(spearman,filename =  "ypd_spearman.jpeg", path=output_path, height=6.3, width=9.5, units = "cm")

```



```{r overlaid plotting function}
# creating the individual plots
library("minpack.lm")
library("ggthemes")
library("ggplot2")
## plotting the sigmoid curves.
xlabel<-expression(paste("aTc[ng/mL]"))

f_plot_sigmoid_curves_overlaid<-
  # plot the fitted line and the individual data points. 
  function(fit_list,frame_list, control_frame_list,label_list_control, xlim, ylim,control_doses){
    formatter<-function(x){x/1000}
    final_plot<-ggplot() 
    # plot the lines
    for (i in c(1:length(fit_list))){
      single_layer_line<- geom_line(aes_(x=x_values, y=fit_list[[i]],
                                         colour=label_list_sigmoid[[i]]), size=1)
      final_plot<-final_plot+single_layer_line
    }
    
    # plot the individual data points
    for (j in c(1:length(frame_list))){
      single_layer_point<- geom_point(aes_(x=frame_list[[j]][,8],y=frame_list[[j]][,1],
                                           colour=label_list_sigmoid[[j]]))   
      final_plot<-final_plot+single_layer_point
    }
    
    ## find the ECs
    
     for(l in c(1:length(ec_list))){
      ec10<-round(ec_list[[l]][1],1)
      ec10_xvalue<-mean(which(round(x_values,1)==ec10))
      ec10_yvalue<-fit_list[[l]][as.integer(ec10_xvalue)]
      
      ec50<-round(ec_list[[l]][2],1)
      ec50_xvalue<-mean(which(round(x_values,1)==ec50))
      ec50_yvalue<-fit_list[[l]][as.integer(ec50_xvalue)]
      
      ec90<-round(ec_list[[l]][3],0)
      ec90_xvalue<-mean(which(round(x_values,0)==ec90))
      ec90_yvalue<-fit_list[[l]][as.integer(ec90_xvalue)]
      
      
      ec_size<-1.5
       ec10_layer<-geom_point(aes_(x=ec10,
                                 y=ec10_yvalue,
                                 shape=paste("EC10"),
                                 colour=label_list_sigmoid[[l]]),size=ec_size) 
      ec50_layer<-geom_point(aes_(x=ec50,
                                 y=ec50_yvalue,
                                 shape=paste("EC50"),
                                 colour=label_list_sigmoid[[l]]),size=ec_size) 
      ec90_layer<-geom_point(aes_(x=ec90,
                                 y=ec90_yvalue,
                                 shape=paste("EC90"),
                                 colour=label_list_sigmoid[[l]]),size=ec_size)
      
      #final_plot<-final_plot + ec10_layer + ec50_layer + ec90_layer
      
    }
    
    # plot the controls
    
    for(k in c(1:length(control_frame_list))){
      dose_control<-control_doses[[k]]
      frame<-control_frame_list[[k]][which(control_frame_list[[k]][,8]==dose_control),]

      single_layer_control<- geom_hline(aes_(yintercept=frame[,1],
                                             linetype=label_list_control[[k]],colour=
                                               label_list_sigmoid[[ceiling(k/2)]]))
      ribbon_layer_control<- geom_ribbon(aes_(ymin=frame[,1]-(frame[,6]*frame[,1]),
                                              ymax=frame[,1]-(frame[,6]*frame[,1]),
                                              x=x_values))

      #final_plot<-final_plot+single_layer_control

    }
    
    
    
    pretty_plot<-final_plot +
      scale_shape_manual(values = c("EC10"=0,
                                    "EC50"=1,
                                    "EC90"=2)) +
      scale_linetype_manual(values=c("longdash","dotdash",
                                     "longdash","dotdash",
                                     "longdash","dotdash",
                                     "longdash","dotdash")) +

     scale_colour_manual(values = colour_palette) +
     scale_x_continuous(breaks = doses_experiment,
                   labels = labels_x_axis,
                   limits = xlim,
                   trans = "log10") +
     scale_y_continuous(limits = ylim, labels=formatter) +
      guides(colour=guide_legend(title = "Strains",nrow=2)) +
      # ggtitle(plot_title) +
      xlab(xlabel) +
      ylab(expression(paste("Fluorescence x","10"^"3","(a.u.)",sep="")))+
      theme(panel.grid.minor = element_blank(),
            legend.direction = "horizontal", legend.position = "none",
            panel.border = element_blank(),
             axis.line = element_line(),
            # axis.text = element_text(size=24),
            # axis.title = element_text(size=24),
            axis.title = element_text(hjust = 1),
            panel.background = element_blank()
            )
    
    return(pretty_plot)
  }

demo(colors)
```


```{r overlaid ethanol, glycerol, proline,sd}

descriptives_to_use<-c(1,6,11,16)
control_descriptives_to_use<-c(3,5,8,10,13,15,18,20)
xlim<-c(0.1,600)
ylim<-c(0,NA)
dose_control<-c("400","400","200","200","200","200","400","400")

colour_palette<-c("#3F0A0B","#731C20","#EE5960","#FE848A")
  #c("pink","firebrick2","tomato3","darkorange1")
  #c("#02085F","#3A05FA","#6E88FC","#91DEFD")
list_of_starting_points<-list(
  c(30000,0.8,20,1,5000),
  c(7000,0.1,2,1,5000),
  c(40000,0.5,5,1,5000),
  c(40000,0.5,2,1,5000)
)
# pick which strains/time_points you want to plot, and their labels
frame_list<-descriptives[descriptives_to_use]
label_list_sigmoid<-c("ypethanol","glycerol","proline","sd")
label_list_control<-c("ype_norepressor","ype_70",
                      "gly_norepressor","gly_70",
                      "pro_norepressor","pro_70",
                      "sd_norepressor","sd_70")

control_frame_error<-df_list[control_descriptives_to_use]
# pick your controls
control_frame_list<-descriptives[control_descriptives_to_use]



#define x axis doses and the labels for plotting
doses_experiment<-c(0.1,1,5,20,60,200,600)
labels_x_axis<- c("0","1","5","20","60","200","600")


# replace 0 values in the doses with 0.1
for(i in c(1:length(frame_list))){
  frame_list[[i]][1,8]<-0.1
}

# generate log distributed x values for smoother line fitting. 
library(emdbook)
x_values<-lseq(min(frame_list[[1]][,8]),
               max(frame_list[[1]][,8]),1000)

strain_list<-label_list_sigmoid

# apply the fitting to each frame with its own individual starting points.
sigmoid_fit_parameters<-mapply(function_curve_fitting,frame_list,list_of_starting_points, 
                                 SIMPLIFY = FALSE)

ec_list<-lapply(sigmoid_fit_parameters,f_ecs)

fit<-lapply(sigmoid_fit_parameters,f_sigmoid_fit,x_values)

sigmoid_plot<-f_plot_sigmoid_curves_overlaid(fit,frame_list, control_frame_list,
                                    label_list_control, xlim, ylim, dose_control)

sigmoid_plot

ggsave(sigmoid_plot,filename =  "overlaid.jpeg", path=output_path, height=6.3, width=9.5, units = "cm")

#---------------------------------------------------------------------------------------------------
## derivative plot



x_values_d<-seq(0,
               max(frame_list[[1]][,8]),length.out=10000)

sigmoid_d_fit<-lapply(sigmoid_fit_parameters,f_d_sigmoid_fit,x_values_d)

ec_y_values<-f_ec_yvalues(sigmoid_d_fit,ec_list)

ylims<-c(0,10000)

strains<-c("a","a","a","a")

colour_by_strain<-TRUE
f_derivative_plot<-f_plot_sigmoid_d(x_values_d, sigmoid_d_fit, label_list_sigmoid, ylims,ec_y_values,strains)

f_derivative_plot
ggsave(f_derivative_plot,filename =  "overlaid_derivative.jpeg", path=output_path, height=6.3, width=9.5
       , units = "cm")


#---------------------------------------------------------------------------------------------------
## spearman plot
spearman_dfs<-descriptives_to_use
label_list_spearman<-label_list_sigmoid


spearman_list<-df_with_size[spearman_dfs]

# replace 0 values in the doses with 0.1
for(i in c(1:length(spearman_list))){
  for(k in c(1:nrow(spearman_list[[i]]))){
    if(spearman_list[[i]][k,4]== 0){
      spearman_list[[i]][k,4]<-0.1
    }
  }
}

spearman_doses<-unique(frame_list[[1]][,8])

variances<-vector("list",length(spearman_list))

for(k in c(1:length(spearman_list))){
  variance<-vector()
  for(i in spearman_doses){
    dataframe<-spearman_list[[k]][which(spearman_list[[k]][,4]==i),]
    var<-cor(dataframe[,3],dataframe[,5], method = "spearman")
    variance<-c(variance,var)
    
  }
  variances[[k]]<-variance
}

spearman<-f_spearman_plot(variances,label_list_spearman, spearman_doses, 0.35)
spearman
ggsave(spearman,filename =  "overlaid_spearman.jpeg", path=output_path, height=6.3, width=9.5, units = "cm")

```

