---
title: "R Notebook"
output: html_notebook
---


```{r set parameters}

source("common_functions.R")
source("stat_functions.R")
source("plotting_functions.R")


library(flowCore)
setwd("C:/Users/aslia/Desktop/pisi/ETH/master project/FACS data/180511_tup1basallevel")

samples<-read.flowSet(pattern = "Specimen")

df_list<-f_df_list(samples,1,1,0,c(2,5,7),5)

strain_names<-c("fry2663","Cfry2676","Dfry2669","Afry70","Bfry2717")
names(df_list)<-strain_names
names(samples@frames)
```


```{r boxplot}
## which strains to compare:
list_of_sequences<-list(
  c(2,3,4,5)
)



title_of_sequences<-c("tup1basallevel_PMThigh"
                      )



mypalette<-c("#ffb419","#5e52e6","#a8d551","#8e00ab","#006512","#d038cc","#917f00","#ff6fe4","#144c21",
             "#c10094","#4fdbcb","#ff4385","#009074","#c0004d","#00b9da","#b54700","#006dcb","#ff6a61",
             "#00939a","#9f0022","#017ab5","#762700","#b5a6ff","#4d5100","#f599ff","#d6c688","#582b80",
             "#ff91b8")
#781e41
#9e5b58)

### boxplots
ylimits_box<-list(c(0,30000)
                  )

widths<-list(0.8)
height_box<-6.3 # saving dimensions
width_box<-9.5
#-----------------------------------------------------------------------------------------------
## boxplots

#first melt dataframes you want to put on the plot into one dataframe

boxplot_frames<-lapply(list_of_sequences,f_melt, df_list,names(df_list),"488 [C]-H" )

summary_stats<-f_stat_summary(as.data.frame(boxplot_frames))

boxplots<-mapply(f_boxplot, boxplot_frames, ylimits_box, widths, SIMPLIFY = FALSE) # create boxplots
#boxplots
names(boxplots)<-title_of_sequences

# then save
output_path<-"C:/Users/aslia/Desktop/pisi/ETH/master project/labbook/paper/figures/figure3"

mapply(f_save,boxplots,names(boxplots),
       MoreArgs = list(output_folder=output_path,output_path="",height=height_box,
                       width=width_box),SIMPLIFY = FALSE)
```


