---
title: "R Notebook"
output: html_notebook
---


```{r set parameters}

source("common_functions.R")
source("stat_functions.R")
source("plotting_functions.R")

mypalette<-c("#a6cee3","#1f78b4","#b2df8a","#33a02c","#fb9a99","#e31a1c",
             "#fdbf6f","#ff7f00","#cab2d6","#6a3d9a","#b15928",
             "black","grey","violetred4","blue", "turquoise","red")


# reading fcs files, t0p1 is the folder for timepoint 0, plate 1 etc.
t0p1_file<-"180423_opmod/opmod"
pattern_read<-"Specimen_001"



output_path<-"C:/Users/aslia/Desktop/pisi/ETH/master project/labbook/plots/april18/180423_opmod" # for saving plots
xlabel<-expression(paste("aTc[ng/mL]", sep = "")) 

starting_well<-1
wells_per_sample<-24


columns<-c(2,5,7) #1=FSC-A, #2=FSC-H, #3=FSC-W, #4=SSC-A, #5=SSC-H, #6=SSC-W, #7= 488 [C]-H


strain_names<-c("2569","2660","2661","2683","70","2598","2599","2601","2602","2603","2551",
                "2564","2565","2566","2659")							

time_points<-c("6h")


label_list<- c("pTDH3, old", #1 
               "RAP1 multiplication", #2
               "RAP1 and GCR1 multiplication",#3
               "pTDH3, new",#4
               "fry70",#5
               "RAP1+A",#6
               "G+ GCR1",#7
               "GCR1down full",#8
               "TATAAAGA",#9
               "TATAAATA",#10
               "2op",#11
               "3op",#12
               "4op",#13
               "5op",#14
               "optimized 5 op"#15
               )


names(label_list)<-strain_names

#---------------------------------------------------------------------------------------------------------------
## pick the values to subset the data with. 

columns <-c(1:4) #columns to be included in the subset
fsch_column <- 1 #column of FSC-W/H
ssch_column <- 2 #column of SSC-W/H
limit_fscw <-300000 #the value for subsetting based on FSC-W/H
limit_sscw <-300000 #the value for subsetting based on SSC-W/H
lower_limit_fscw <-25000 #the value for subsetting based on FSC-W/H, lower limit
lower_limit_sscw <-0000 #the value for subsetting based on SSC-W/H, lower limit

size_subset<-TRUE # set to TRUE if you want to use size_subsetted data, otherwise false.

#---------------------------------------------------------------------------------------------------------------
## descriptive statistics

cols_descriptives<-3


#---------------------------------------------------------------------------------------------------------------

## size plots
fscw_column_size<-1
sscw_column_size<-2
xlab_size<-"FSC-W"
ylab_size<-"SSC-W"
ylimits_size<-c(0000,NA)
xlimits_size<-c(0000,NA)

labels_for_grid_size<-time_points # labels for the plots in the 2x2 grid

height_size<-10 # saving dimensions
width_size<-15

#---------------------------------------------------------------------------------------------------------------

## histograms
list_of_sequences<-list(c(2,3,4,14,15),
                        c(4,6,7,8,9,10,13),
                        c(4,11,12,13,14))

title_of_sequences<-list("multiplications",
                         "4op",
                         "op placement")

xlimits_his<-list(c(0,100000),c(0,100000),c(0,100000))
ylimits_his<-c(0,NA)
legend_position_his<-c(0.8,0.8)
size_value_his<-1
guide_title_his<-"strains"
ncol_legend_his<-2
column_to_plot_his<-3

height_his<-10
width_his<-15
#---------------------------------------------------------------------------------------------------------------

#boxplots
ylimits_box<-list(c(0,100000))
widths<-list(0.8,0.8,0.8,0.8,0.8,0.8)

height_box<-10
width_box<-15


```


```{r}
## create a list of dataframes, each df being one well.

f_df<-function(flowset){
  frame_list<-list()
  for(i in c(1:length(flowset))){
    frame<-as.data.frame(flowset[[i]]@exprs[,c(2,5,7)]) # pick FSC-W, SSC-W, 488(C)-H and 561(E)-H channels.
    frame_list[[i]]<-frame
  }
  return(frame_list)
}

f_subset<-function(dataframe, fsc_upper_limit, fsc_lower_limit, ssc_upper_limit, ssc_lower_limit){
  new_dataframe<-subset(dataframe, dataframe[,1]<fsc_upper_limit &
                                   dataframe[,1]>fsc_lower_limit &
                                   dataframe[,2]<ssc_upper_limit &
                                   dataframe[,2]>ssc_lower_limit)
  return(new_dataframe)
}

## t1 (4h)
# uninduced_t1<-f_df(t1p1)[c(1:19)]
# induced_t1<-f_df(t1p1)[c(20:38)]


uninduced_t0<-f_df(t0p1)
df_list<-uninduced_t0
uninduced_t0<-lapply(uninduced_t0,f_subset,300000,25000,300000,0)



```


