---
title: "R Notebook"
output: html_notebook
---

```{r read flowSets}

source("common_functions.R")
source("stat_functions.R")
source("plotting_functions.R")

t0p1_file<-"180125_5op_tetrfusion/p1"
pattern_read<-"Specimen_001"


output_path<-"C:/Users/aslia/Desktop/pisi/ETH/master project/labbook/paper/figures/figure3"
# create folders named size, svf, histograms, boxplots under this directory. 

columns<-c(3,6,7) # usually fsc-h, ssc-h, and 488C-h
fsch_column<-1 # the index in "columns"
ssch_column<-2 # the index in "columns"
size_subset<-FALSE # set to true to subset based on fsch/ssch
fsc_h_lower_limit<-50000
fsc_h_upper_limit<-73000
ssc_h_lower_limit<-0
ssc_h_upper_limit<-200000


## naming & labels

strain_names<-c("2661","70","2663","2681","2681v2","2664","2665","2666","2667","2669","2675","2676","2668",
                "2672","2672v2","2678","2678v2","2674v13","2674v14","2682","2682v2","2683","2683v2","2677",
                "2677v2","2674v1","2674v2","2674v3","2674v4","2674v5","2674v6","2674v7","2674v8","2674v9",
                "2674v10","2674v11","2674v12")

label_list<-c(
"no repressor", #1 
"fry70", #2

"pAct1_TetR-NLS", #3 
"pAct1_TetR-NLS-NLSv1", #4 chosen
"pAct1_TetR-NLS-NLSv2", #5

"pAct1_TetR-NLS-GST", #6
"pAct1_TetR-NLS-GST-NLS", #7
"pAct1_TetR-NLS-MBP", #8
"pAct1_TetR-NLS-MBP-NLS", #9 

"pAct1_TetR-NLS-TUP1", #10
"pVph1_TetR-NLS", #11
"pVph1_TetR-NLS-TUP1", #12
"pVph1_TetR-NLS-MBP-NLS", #13

"pTDH3_TetR-NLSv1", #14 chosen
"pTDH3_TetR-NLSv2", #15 

"wrong strain1", #16 
"wrong strain", #17 
"5 op NF strain v13", #18 
"5 op NF strain v14", #19 
"2op pAct1_TetR-NLS-NLSv1", #20 chosen
"2op pAct1_TetR-NLS-NLSv2", #21 
"pTDH3_citrinev1", #22 chosen
"pTDH3_citrinev2", #23 
"2op pVph1_TetR-NLS-TUP1v1", #24 chosen
"2op pVph1_TetR-NLS-TUP1v2", #25

"5 op NF strain v1", #26
"5 op NF strain v2", #27 
"5 op NF strain v3", #28
"5 op NF strain v4", #29 
"5 op NF strain v5", #30
"5 op NF strain v6", #31 
"5 op NF strain v7", #32
"5 op NF strain v8", #33 
"5 op NF strain v9", #34
"5 op NF strain v10", #35  
"5 op NF strain v11", #36 
"5 op NF strain v12" #37 
)


## which strains to compare:
list_of_sequences<-list(
  c(2,10,9,8,7,6,4,3)
)

title_of_sequences<-c("tetrfusions"
                      )



mypalette<-c("#ffb419","#5e52e6","#a8d551","#8e00ab","#006512","#d038cc","#917f00","#ff6fe4","#144c21",
             "#c10094","#4fdbcb","#ff4385","#009074","#c0004d","#00b9da","#b54700","#006dcb","#ff6a61",
             "#00939a","#9f0022","#017ab5","#762700","#b5a6ff","#4d5100","#f599ff","#d6c688","#582b80",
             "#ff91b8")
#781e41
#9e5b58)

### boxplots
ylimits_box<-list(c(0,4000)
                  )

widths<-list(0.8)
height_box<- 6 # saving dimensions
width_box<-9.04

 
```

```{r}


## read fcs files as a flowset
t0p1<-f_read(t0p1_file,pattern_read)

#-----------------------------------------------------------------------------------------------

## create the dataframe list
df_list<-f_df_comparison(t0p1,columns,fsch_column, ssch_column, fsc_h_lower_limit,
                fsc_h_upper_limit,ssc_h_lower_limit, ssc_h_upper_limit)

names(df_list)<-strain_names

#-----------------------------------------------------------------------------------------------
## boxplots

#first melt dataframes you want to put on the plot into one dataframe

boxplot_frames<-lapply(list_of_sequences,f_melt, df_list, label_list,"488 [C]-H" )

boxplots<-mapply(f_boxplot, boxplot_frames, ylimits_box, widths, SIMPLIFY = FALSE) # create boxplots
names(boxplots)<-title_of_sequences

boxplots

# then save
mapply(f_save,boxplots,names(boxplots),
       MoreArgs = list(output_folder=output_path,height=height_box,
                       width=width_box),SIMPLIFY = FALSE)

mapply(f_save_pdf,boxplots,names(boxplots),
       MoreArgs = list(output_folder=output_path,height=height_box,
                       width=width_box),SIMPLIFY = FALSE)


```

```{r effect of nls}
cols_descriptives<-3
descriptives<-lapply(df_list,f_descriptives_comp,column=cols_descriptives)
names(descriptives)<-label_list

pairs_to_compare<-descriptives[c(3,4,6,7,8,9,2,8)]


fold_repression_list<-vector()

for(i in seq(1,length(pairs_to_compare),2)){
  print(i)
  fold_repression<-pairs_to_compare[[i+1]][1,1]/pairs_to_compare[[i]][1,1]
  fold_repression_list<-c(fold_repression_list,fold_repression)
}

fold_repression_list



```

