---
title: "R Notebook"
output: html_notebook
---

```{r}


library(ggplot2)
source("common_functions.R")
source("stat_functions.R")

t0p1_file<-"180815_washnarrest/measurement"
t0p2_file<-"180815_washnarrest/controls_atc"
t0p3_file<-"180815_washnarrest/controls_parent"
t0p4_file<-"180803_washnarrest/controls"

output_path<-"C:/Users/aslia/Desktop/pisi/ETH/master project/labbook/plots/august18/180815_wash&arrest" # for saving plots
pattern_read<-""

starting_well<-1


columns_to_include<-c(3,6,7) #1=FSC-A, #2=FSC-H, #3=FSC-W, #4=SSC-A, #5=SSC-H, #6=SSC-W, #7= 488 [C]-H

 
#time_points<-c("0min","30min","60min","90min","120min","150min","180min","210min","240min","270min","300min","330min","21h")
time_points<-c(0,60,90,120,360,1260)

label_list<- c("tor2_t0",
               "tor2_t60",
               "tor2_t90",
               "tor2_t120",
               "tor2_t150",
               "tor2_t180",
               "tor2_t240",
               "tor2_t300",
               "tor2_t360",
               "tor2_t21h",
               
               "tor2atc_t0",
               "tor2atc_t360",
               "tor2atc_t21h",
               
               "parent_t0",
               "parent_t360",
               "parent_t21h",
               
               "parent_Nstarved",
               "diploid_exponential"
               )


#---------------------------------------------------------------------------------------------------------------
## pick the values to subset the data with. 

columns <-c(1:4) #columns to be included in the subset
col_fscw <- 1 #column of FSC-W/H
col_sscw <- 2 #column of SSC-W/H
limit_fscw <-90000 #the value for subsetting based on FSC-W/H
limit_sscw <-90000 #the value for subsetting based on SSC-W/H
lower_limit_fscw <-000 #the value for subsetting based on FSC-W/H, lower limit
lower_limit_sscw <-0000 #the value for subsetting based on SSC-W/H, lower limit

size_subset<-FALSE # set to TRUE if you want to use size_subsetted data, otherwise false.

#---------------------------------------------------------------------------------------------------------------



```


```{r}


f_time_lapse_plot<-function(dataframe, title, ylims, xlims){
  
  final_plot<- ggplot(dataframe) +
    geom_histogram(aes_(x=dataframe[,3]), binwidth = 100) +
    facet_wrap(~dataframe[,4]) +
    
    theme_bw() +
    ggtitle(title) +
    xlab("Fluorescence (a.u.)") +
    xlim(xlims) +
    ylim(ylims)
  
  return(final_plot)
  
}

ylims<-list(c(0,400), c(0,400),c(0,400),c(0,100),c(0,100))
xlims<-list(c(0,40000),c(0,40000),c(0,40000),c(0,80000),c(0,125000))
titles<-list("tor2, - aTc", "tor2, + aTc", "parent", "parent (N starved)", "diploid strain")
time_lapse_plots<-mapply(f_time_lapse_plot, df_list, titles, ylims, xlims, SIMPLIFY = F)

time_lapse_plots

mapply(f_save,time_lapse_plots,names(df_list),
        MoreArgs = list(output_path, "", 10, 15), SIMPLIFY = F)





```


```{r}

ggplot(df_list[[1]]) +
  geom_density2d(aes(x=df_list[[1]][,1], y=df_list[[1]][,3])) +
  facet_wrap(~df_list[[1]][,4])


ggplot(df_list[[2]]) +
  geom_density2d(aes(x=df_list[[2]][,1], y=df_list[[2]][,3])) +
  facet_wrap(~df_list[[2]][,4])



n<-2
ggplot(df_with_size[[n]]) +
  geom_density_2d(aes(df_with_size[[n]][,5], df_with_size[[n]][,3])) +
  facet_wrap(~df_with_size[[n]][,4])


```

