---
title: "R Notebook"
output: html_notebook
---


```{r set parameters}

source("common_functions.R")
source("stat_functions.R")
source("plotting_functions.R")


## colour scale
plot_palette<-c(
"0"="#867236",
"0.001"="#6343c6",
"0.005"="#addf42",
"0.01"="#bf4dd6",
"0.05"="#63d654",
"0.1"="#d148a3",
"0.5"="#d7ca3b",
"0.7"="#6e74cc",
"1"="#5c8f38",
"2"="#77397a",
"3"="#74dc9e",
"4"="#cf466b",
"5"="#76d5d7",
"7"="#de4e34",
"9"="#8cadd1",
"10"="#d6913d",
"12"="#4b5e7d",
"15"="#cad17b",
"25"="#d292c6",
"35"="#435738",
"60"="#98432a",
"100"="#5b957b",
"200"="#7c4a51",
"no repressor"="#ccccb0",
"fry70"="black")



# reading fcs files, t0p1 is the folder for timepoint 0, plate 1 etc.
t0p1_file<-"180215_rnr2doseresponse/4.5h"
t0p2_file<-"180215_rnr2doseresponse/4.5h/2663"
t1p1_file<-"180215_rnr2doseresponse/4.5h/controls"
pattern_read<-"Specimen_001"


output_path<-"C:/Users/aslia/Desktop/pisi/ETH/master project/labbook/paper/figures/figure3" # for saving plots
xlabel<-expression(paste("aTc[ng/",mu,"L]", sep = "")) 

starting_well<-1
wells_per_sample<-23
wells_per_sample_p2<-12

experiment_doses_p2<-c(0,0.01,0.1,1,3,5,9,12,25,60,100,200)
experiment_doses<-c(0,0.001,0.005,0.01,0.05,0.1,0.5,0.7,1,2,3,4,5,7,9,10,12,15,25,35,60,100,200)
experiment_doses_controls<-c(0,200)

columns_to_include<-c(3,6,7) #1=FSC-A, #2=FSC-H, #3=FSC-W, #4=SSC-A, #5=SSC-H, #6=SSC-W, #7= 488 [C]-H


strain_names<-c("2717","2669","2676","70","2661") 
time_points<-c("4.5h")
controls_names<-c("70","2661")

label_list<- c("optimizedP_citrine + pRNR2_TetR_NLS-TUP1",
               "optimizedP_citrine + pAct1_TetR_NLS-TUP1",
               "optimizedP_citrine + pVph1_TetR_NLS-TUP1",
               "fry70",
               "no repressor"
               )

label_list_other<-("optimizedP_citrine + pAct1_TetR_NLS")

names(label_list)<-strain_names

label_list_controls<-c("fry70",
                       "no repressor"
                       )

names(label_list_controls)<-controls_names
#---------------------------------------------------------------------------------------------------------------
## pick the values to subset the data with. 

columns <-c(1:4) #columns to be included in the subset
col_fscw <- 1 #column of FSC-W/H
col_sscw <- 2 #column of SSC-W/H
limit_fscw <-100000 #the value for subsetting based on FSC-W/H
limit_sscw <-100000 #the value for subsetting based on SSC-W/H
lower_limit_fscw <-000 #the value for subsetting based on FSC-W/H, lower limit
lower_limit_sscw <-0000 #the value for subsetting based on SSC-W/H, lower limit

size_subset<-TRUE # set to TRUE if you want to use size_subsetted data, otherwise false.

#---------------------------------------------------------------------------------------------------------------
## descriptive statistics

dose_descriptives<-experiment_doses
cols_descriptives<-3


#---------------------------------------------------------------------------------------------------------------
## smoothed dose response curves of the strains you want

descriptive_sequence<-c(1:4) #pick the strains at given timepoints
label_list_smooth<-label_list[c(1:4)]
timepoint_used<-1
number_of_timepoints<-1
ncol_legend_smooth<-2
statistic_to_use<-1 #1 is median, 2 is mean
scale_x_breaks_smooth<-experiment_doses
scale_x_labels_smooth<-experiment_doses
legend_title_smooth<-"Strain"
plot_title_smooth<-"Dose Response Curves, 4.5h"
xlab_smooth<-xlabel
ylab_smooth<-"Fluorescence (a.u.)"
legend_direction_smooth<-"vertical"
legend_position_smooth<-c(0.8,0.2)
additional_arguments_smooth<-NULL
time_point_smooth<-"4.5h" # to be used in the filename when saving the plot.

height_smooth<-10 # the height and width of the plot to be saved
width_smooth<-15
#---------------------------------------------------------------------------------------------------------------

## size plots
fscw_column_size<-1
sscw_column_size<-2
xlab_size<-"FSC-W"
ylab_size<-"SSC-W"
ylimits_size<-c(40000,NA)
xlimits_size<-c(40000,NA)

labels_for_grid_size<-time_points # labels for the plots in the 2x2 grid

height_size<-10 # saving dimensions
width_size<-15

#---------------------------------------------------------------------------------------------------------------

## histograms

doses_histogram<-list(experiment_doses,experiment_doses,experiment_doses,experiment_doses_p2) # the doses you want to plot. if you change this, you should change the manual colour scale inside the function as well. 

labels_histogram<-c("0","0.001","0.005","0.01","0.05","0.1","0.5","0.7","1","2","3","4","5","7",
                    "9","10","12","15","25","35","60","100","200")
breaks_histogram<-c(labels_histogram, label_list_controls)

control_sequence<-c(1,2)
column_to_plot_controls<-3

size_histogram<- 1.3 # size of the lines
legend_title_histogram<-xlabel
legend_ncol_histogram<-2
legend_position_histogram<-c(0.7,0.8)
xlimits_histogram<-c(0,50000)
ylimits_histogram<-c(0,0.001)

grid_labels_histograms<-time_points # labels for the plots in the 2x2 grid

height_histograms<-10 # saving dimensions
width_histograms<-15
#---------------------------------------------------------------------------------------------------------------

## descriptive plots
palette<-c("4.5h"="purple")
colour_labels<-time_points
scale_x_breaks<-experiment_doses
ylab_title<-"Fluorescence (a.u.)"
xlab_title<-xlabel
legend_title<-"Time Point"
stat_columns_1<-c(1,6)
stat_columns_2<-c(2,7)
size_value_descriptives<-4
height_descriptives<-10
width_descriptives<-15

#----------------------------------------------------------------------------------------------------------

## sigmoid fits
descriptives_to_use_sigmoid<-c(1,2,3)
labels_to_use<-c(1,2,3)
colour_palette<-c("red","blue", "orange","green","black","purple","pink") # define the colour palette for plotting
# define the plot title, xlabel
plot_title<-"Dose Response Curves, 5h"
xlabel<-expression(paste("aTc[ng/mL]"))

# pick controls for the plot
controls_to_use_sigmoid<-c(4,5)
# define starting points for the fitting for each curve: c(a,b,c,d)
# a is the upper asymptote, b is the steepest slope, c is the x axis value at b, e is the lower 
# asymptote. you can define these individually for every curve. 
# d is the symmetry parameter. if =1, the curve is symmetrical around EC50. 
# a negative b gives you an inverse sigmoid, a positive one gives you a sigmoid. or does it? 
list_of_starting_points<-list(
  c(30000,1,8,1,200),
  c(30000,0.8,25,1,200),
  c(30000,1,7,1,200)
)

time_point_sigmoid<-"5h"
height_sigmoid<-10
width_sigmoid<-15

## derivative of sigmoid fit

label_list_derivative<-c("pRNR2","pAct1","pVph1")
#----------------------------------------------------------------------------------------------------------
## size vs. induction plots

x_breaks_density<-labels_histogram
legend_title_density<-xlabel
ncol_legend_density<-2
legend_position_density<-c(0.15,0.68)
size_column<-5
citrine_column<-3
dose_column<-4

doses_size_vs_induction<-experiment_doses

# ist(experiment_doses,experiment_doses,experiment_doses,experiment_doses_p2,
#                               c(0,200),c(0,200)) # the doses you want to plot. if you change this, you should change the manual colour scale inside the function as well. 

labels_size_vs_induction<-labels_histogram  #labels that will appear on the legend, and that determine the colour_scale_manual mappings. If you change anything here, change it in the colour scale inside the function as well. 

grid_labels_density<-time_points

height_density<-10
width_density<-15
#----------------------------------------------------------------------------------------------------------## QQPLOTS
# in the dataframelist1/2, pick the strain you want to plot. in the doses part, you can specify which 
# dose is to be plotted. in columns, pick which column is to be plotted. dataframelist1 and 2 will be paired in each qqplot (i.e. dataframelist1[1] is plotted against dataframelist2[[1]])
dataframelist1<-c(1,1,1,2,2,2,4,4,4,4,4,4,5,6,1,1,1,1,1,1,rep(1,6))
dataframelist1_doses<-c(0,200,5,0,200,5,0,200,5,0,200,5,0,0,1,2,0.5,0.7,0.1,0.05,
                        1,2,0.5,0.7,0.1,0.05)
dataframelist1_columns<-rep(3,length(dataframelist1))
dataframelist2<-c(3,3,3,3,3,3,1,1,1,2,2,2,1,1,3,3,3,3,3,3,rep(5,6))
dataframelist2_doses<-c(0,200,5,0,200,5,0,200,5,0,200,5,0,200,1,2,0.5,0.7,0.1,0.05,
                        0,0,0,0,0,0)
dataframelist2_columns<-rep(3,length(dataframelist2))

xlims_qqplot<-list(c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),
                   c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),
                   c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),
                   c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA))
ylims_qqplot<-list(c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),
                   c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),
                   c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),
                   c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA),c(0,NA))

titles_qqplot<-c("rnr2 vs vph1,0atc",
          "rnr2 vs vph1,200atc",
          "rnr2 vs vph1,5atc",
          "act1 vs vph1,0atc",
          "act1 vs vph1,200atc",
          "act1 vs vph1,5atc",
          "tetr vs rnr_tup1,0atc",
          "tetr vs rnr_tup1,200atc",
          "tetr vs rnr_tup1,5atc",
          "tetr vs act1_tup1,0atc",
          "tetr vs act1_tup1,200atc",
          "tetr vs act1_tup1,5atc",
          "fry70 vs rnr2",
          "no repressor vs rnr2",
          "rnr2 vs vph1, 1atc",
          "rnr2 vs vph1, 2atc",
          "rnr2 vs vph1, 0.5atc",
          "rnr2 vs vph1, 0.7atc",
          "rnr2 vs vph1, 0.1atc",
          "rnr2 vs vph1, 0.05atc",
          
          "rnr2 vs fry70, 1atc",
          "rnr2 vs fry701, 2atc",
          "rnr2 vs fry70, 0.5atc",
          "rnr2 vs fry70, 0.7atc",
          "rnr2 vs fry70, 0.1atc",
          "rnr2 vs fry70, 0.05atc"
          
          )

label_list_qq<-c(label_list,label_list_controls)
width_qq<-15
height_qq<-10
```


```{r}
source("facs_script.R")

qqplots

```


