---
title: "R Notebook"
output: html_notebook
---


```{r set parameters}

source("common_functions.R")
source("stat_functions.R")
source("plotting_functions.R")



## colour scale


# reading fcs files, t0p1 is the folder for timepoint 0, plate 1 etc.
t0p1_file<-"180427_timeofinduction/t0"
t1p1_file<-"180427_timeofinduction/30min"
t2p1_file<-"180427_timeofinduction/1h"
t3p1_file<-"180427_timeofinduction/90min"
t4p1_file<-"180427_timeofinduction/150min"
t5p1_file<-"180427_timeofinduction/210min"
t6p1_file<-"180427_timeofinduction/4h"
t7p1_file<-"180427_timeofinduction/6h"
t7p2_file<-"180427_timeofinduction/t0/controls"
pattern_read<-"Specimen_001"


output_path<-"C:/Users/aslia/Desktop/pisi/ETH/master project/labbook/plots/april18/180427_timeofinduction" # for saving plots
xlabel<-expression(paste("aTc[ng/mL]", sep = "")) 

starting_well<-1
wells_per_sample<-3

experiment_doses<- c("1","2","3")


columns_to_include<-c(2,5,7) #1=FSC-A, #2=FSC-H, #3=FSC-W, #4=SSC-A, #5=SSC-H, #6=SSC-W, #7= 488 [C]-H


strain_names<-c("2674","2759","2663","2669",
                "2675","2676","2717","2689",
                "2688","2664","2665","2666",
                "2667")
  
  # c("2674","2674","2674","2759","2759","2759","2663","2663","2663","2669","2669","2669",
  #               "2675","2675","2675","2676","2676","2676","2717","2717","2717","2689","2689","2689",
  #               "2688","2688","2688","2664","2664","2664","2665","2665","2665","2666","2666","2666",
  #               "2667","2667","2667")

control_strain_names<-c("70","70","70","2661","2661","2661","2683","2683","2683")


time_points<-c("0min","30min","60min","90min","150min","210min","240min","360min")

label_list<- c("7op final, only NF",
               "7op final, NF+rnr2_tup1", 
               "7op final, pAct1_TetR",
               "7op final, pAct1_TetR-TUP1",
               "7op final, pVph1_TetR",
               "7op final, pVph1_TetR-TUP1",
               "7op final, pRNR2_TetR-TUP1",
               "7op final, pAct1_TetR-TUP1C425",
               "7op final, pVph1_TetR-TUP1C425",
               "7op final, pAct1_TetR-GST",
               "7op final, pAct1_TetR-GST-2xNLS",
               "7op final, pAct1_TetR-MBP",
               "7op final, pAct1_TetR-MBP-2xNLS"
               )
label_list_control<-c(
               
               "no repressor",
               "pTDH3_citrine",
               "fry70")

names(label_list)<-strain_names

#---------------------------------------------------------------------------------------------------------------
## pick the values to subset the data with. 

columns <-c(1:4) #columns to be included in the subset
col_fscw <- 1 #column of FSC-W/H
col_sscw <- 2 #column of SSC-W/H
limit_fscw <-90000 #the value for subsetting based on FSC-W/H
limit_sscw <-90000 #the value for subsetting based on SSC-W/H
lower_limit_fscw <-000 #the value for subsetting based on FSC-W/H, lower limit
lower_limit_sscw <-0000 #the value for subsetting based on SSC-W/H, lower limit

size_subset<-FALSE # set to TRUE if you want to use size_subsetted data, otherwise false.

#---------------------------------------------------------------------------------------------------------------
## descriptive statistics

dose_descriptives<-experiment_doses
cols_descriptives<-3


#---------------------------------------------------------------------------------------------------------------
## smoothed dose response curves of the strains you want

descriptive_sequence<-c(1:2) #pick the strains at given timepoints
label_list_smooth<-label_list[c(1:2)]
timepoint_used<-1
number_of_timepoints<-1
ncol_legend_smooth<-2
statistic_to_use<-2 #1 is median, 2 is mean
scale_x_breaks_smooth<-experiment_doses
scale_x_labels_smooth<-experiment_doses
legend_title_smooth<-"Strain"
plot_title_smooth<-"Dose Response Curves, 6h"
xlab_smooth<-xlabel
ylab_smooth<-"Fluorescence (a.u.)"
legend_direction_smooth<-"vertical"
legend_position_smooth<-c(0.8,0.2)
additional_arguments_smooth<-NULL
time_point_smooth<-"6h" # to be used in the filename when saving the plot.

height_smooth<-10 # the height and width of the plot to be saved
width_smooth<-15
#---------------------------------------------------------------------------------------------------------------

## size plots
fscw_column_size<-1
sscw_column_size<-2
xlab_size<-"FSC-W"
ylab_size<-"SSC-W"
ylimits_size<-c(40000,NA)
xlimits_size<-c(40000,NA)

labels_for_grid_size<-time_points # labels for the plots in the 2x2 grid

height_size<-10 # saving dimensions
width_size<-15

#---------------------------------------------------------------------------------------------------------------

## histograms
dfs_to_histogram<-c(1,2)
doses_histogram<-experiment_doses # the doses you want to plot. if you change this, you should change the manual colour scale inside the function as well. 

labels_histogram<-c("0","0.2","1","2","3","4","5","6","8","10","13","15",
                    "17","20","26","30","35","45","50","65","80","100","200","400",
                    "fry70","tdh3","no repressor") 
breaks_histogram<-labels_histogram

dose_column<-4 #the column with doses 
citrine_column<-3 # column with citrine measurement

control_sequence<-c(3,4,5)
control_labels<-c("fry70","no repressor","tdh3")

size_histogram<- 1.3 # size of the lines
legend_title_histogram<-xlabel
legend_ncol_histogram<-2
legend_position_histogram<-c(0.7,0.8)
xlimits_histogram<-c(0,60000)
ylimits_histogram<-c(0,0.0005)

grid_labels_histograms<-time_points # labels for the plots in the 2x2 grid

height_histograms<-10 # saving dimensions
width_histograms<-15


names_individual_histograms<-c("histogram_gridNF.jpeg","histogram_gridAct1.jpeg") # names for saving the plots
x_limits_individual_histogram<-c(0,50000)
x_breaks_individual_histogram<-c(0,9000,25000,50000)
y_breaks_individual_histogram<-c(0,0.0001,0.0002)
y_limits_individual_histogram<-c(0,0.0001)
#---------------------------------------------------------------------------------------------------------------

## descriptive plots
palette<-c("6h"="purple")
colour_labels<-time_points
scale_x_breaks<-experiment_doses
ylab_title<-"Fluorescence (a.u.)"
xlab_title<-xlabel
legend_title<-"Time Point"
stat_columns_1<-c(1,6)
stat_columns_2<-c(2,7)
size_value_descriptives<-4
height_descriptives<-10
width_descriptives<-15

#----------------------------------------------------------------------------------------------------------

## sigmoid fits
descriptives_to_use_sigmoid<-c(1,2)
labels_to_use<-c(1,2)
colour_palette<-c("red","blue", "orange","green","black") # define the colour palette for plotting
# define the plot title, xlabel
plot_title<-"Dose Response Curves, 24"
xlabel<-expression(paste("aTc[ng/mL]"))

# pick controls for the plot
controls_to_use_sigmoid<-c(3,4,5)
# define starting points for the fitting for each curve: c(a,b,c,d)
# a is the upper asymptote, b is the steepest slope, c is the x axis value at b, e is the lower 
# asymptote. you can define these individually for every curve. 
# d is the symmetry parameter. if =1, the curve is symmetrical around EC50. 
# a negative b gives you an inverse sigmoid, a positive one gives you a sigmoid. or does it? 
list_of_starting_points<-list(
  c(30000,0.8,26,0.2,3000),
  c(30000,0.01,1,10,3000)
)

time_point_sigmoid<-"24h"
height_sigmoid<-10
width_sigmoid<-15

## derivative of sigmoid fit

label_list_derivative<-c("NF","pAct1")
#----------------------------------------------------------------------------------------------------------
## size vs. induction plots

palette_density<-plot_palette
x_breaks_density<-labels_histogram
legend_title_density<-xlabel
ncol_legend_density<-2
legend_position_density<-c(0.15,0.68)
size_column<-5
citrine_column<-3
dose_column<-4

doses_size_vs_induction<-experiment_doses # the doses you want to plot. if you change this, you should change the manual colour scale inside the function as well. 

labels_size_vs_induction<-labels_histogram  #labels that will appear on the legend, and that determine the colour_scale_manual mappings. If you change anything here, change it in the colour scale inside the function as well. 

grid_labels_density<-time_points

height_density<-10
width_density<-15

#----------------------------------------------------------------------------------------------------------## QQPLOTS
# in the dataframelist1/2, pick the strain you want to plot. in the doses part, you can specify which 
# dose is to be plotted. in columns, pick which column is to be plotted. dataframelist1 and 2 will be paired in each qqplot (i.e. dataframelist1[1] is plotted against dataframelist2[[1]])
dataframelist1<-c(1,1,1)
dataframelist1_doses<-c(0,200,400)
dataframelist1_columns<-c(3,3,3)
dataframelist2<-c(2,2,2)
dataframelist2_doses<-c(0,200,400)
dataframelist2_columns<-c(3,3,3)

xlims_qqplot<-list(c(0,NA),c(0,NA),c(0,NA))
ylims_qqplot<-list(c(0,NA),c(0,NA),c(0,NA))

titles_qqplot<-c("NF vs pAct1,0atc",
          "NF vs pAct1,200atc",
          "NF vs pAct1,400atc"
          )

width_qq<-15
height_qq<-10

```


```{r}
source("facs_script.R")


df_list_names

```




```{r}

library(reshape2)
dfs_to_melt<-df_list[c(1,2,14,15,27,28,40,41,53,54,66,67,79,80,92,93)]
time_point_list<-c(0,0,30,30,60,60,90,90,150,150,210,210,240,240,360,360)
strain_list<-c(1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2)

for(i in c(1:length(dfs_to_melt))){
  
  df<-dfs_to_melt[[i]]
  time_point<-time_point_list[i]
  strain<-strain_list[[i]]
  df<-cbind(df[,3],rep(time_point,nrow(df)),rep(strain,nrow(df)))
  colnames(df)<-c("488 [C]-H","time_point","strain")
  dfs_to_melt[[i]]<-as.data.frame(df)
  
}


figure_dfs<-melt(dfs_to_melt, measure.var=1)
figure_dfs<-droplevels(figure_dfs)
figure_dfs[,1]<-as.factor(figure_dfs[,1])
figure_dfs[,2]<-as.numeric(figure_dfs[,2])


#scales::seq_gradient_pal("lightblue", "darkblue", "Lab")(seq(0,1,length.out=11))

ggplot(figure_dfs) +
    
    geom_density(aes(x=value,colour=time_point)) +
    
    facet_wrap(~strain, ncol=1,strip.position = "right") +
    theme(legend.position = c(0.2,0.8)) +
    guides(colour=guide_legend(ncol = 2, title="")) +
    theme_bw() +
    scale_x_log10(limits=c(100,200000)) +
    scale_colour_manual(values = c("#ADD8E6", #1
                                   "#A1C2DD", #2
                                   "#95ACD4", #3
                                   "#8997CB", #4
                                  # "#7C82C2", #5
                                   "#6E6DB9", #6
                                   "#6059B0", #7
                                   "#5145A7", #8
                                   #"#3F309E", #9
                                   "#291B94" #10
                                  # "#00008B"  #11
                                   ))
  #  ylim(0,0.0005)



```

