---
title: "R Notebook"
output: html_notebook
---


```{r set parameters}

source("common_functions.R")
source("stat_functions.R")
source("plotting_functions.R")


## colour scale
## colour scale
plot_palette<-c(
"0"="#867236",
"0.5"="#6343c6",
"1"="#addf42",
"2"="#bf4dd6",
"3"="#63d654",
"4"="#d148a3",
"5"="#d7ca3b",
"6"="#6e74cc",
"7"="#5c8f38",
"9"="#77397a",
"10"="#74dc9e",
"12"="#cf466b",
"14"="#76d5d7",
"16"="#de4e34",
"18"="#8cadd1",
"20"="#d6913d",
"23"="#4b5e7d",
"25"="#cad17b",
"27"="#d292c6",
"30"="#435738",
"45"="#98432a",
"60"="#5b957b",
"100"="#7c4a51",
"200"="#ccccb0",
"fry70"="black",
"no repressor"="black",
"tdh3"="blue")



# reading fcs files, t0p1 is the folder for timepoint 0, plate 1 etc.
t0p1_file<-"180306_media_longterm/24h"
pattern_read<-"Specimen_001"


output_path<-"C:/Users/aslia/Desktop/pisi/ETH/master project/labbook/plots/march18/180307_longtermmedia" # for saving plots
xlabel<-expression(paste("aTc[ng/mL]", sep = "")) 

starting_well<-1
wells_per_sample<-1

experiment_doses<-c(500)
columns_to_include<-c(3,6,7) #1=FSC-A, #2=FSC-H, #3=FSC-W, #4=SSC-A, #5=SSC-H, #6=SSC-W, #7= 488 [C]-H


strain_names<-c("2561e","2562e","2551e","70e",
                "2561g","2562g","2551g","70g",
                "2561p","2562p","2551p","70p") # all of them are just one strain, FRY2561
time_points<-c("24h")

label_list<- c("2op NF_ethanol",
               "2op pAct1_ethanol",
               "no repressor_ethanol",
               "fry70_ethanol",
               "2op NF_glycerol",
               "2op pAct1_glycerol",
               "no repressor_glycerol",
               "fry70_glycerol",
               "2op NF_proline",
               "2op pAct1_proline",
               "no repressor_proline",
               "fry70_proline"
               )

names(label_list)<-strain_names

#---------------------------------------------------------------------------------------------------------------
## pick the values to subset the data with. 

columns <-c(1:4) #columns to be included in the subset
col_fscw <- 1 #column of FSC-W/H
col_sscw <- 2 #column of SSC-W/H
limit_fscw <-72000 #the value for subsetting based on FSC-W/H
limit_sscw <-100000 #the value for subsetting based on SSC-W/H
lower_limit_fscw <-68000 #the value for subsetting based on FSC-W/H, lower limit
lower_limit_sscw <-40000 #the value for subsetting based on SSC-W/H, lower limit

size_subset<-FALSE # set to TRUE if you want to use size_subsetted data, otherwise false.

#---------------------------------------------------------------------------------------------------------------
## descriptive statistics

dose_descriptives<-experiment_doses
cols_descriptives<-3


#---------------------------------------------------------------------------------------------------------------
## smoothed dose response curves of the strains you want

descriptive_sequence<-c(1:2) #pick the strains at given timepoints
label_list_smooth<-label_list[c(1:2)]
timepoint_used<-1
number_of_timepoints<-1
ncol_legend_smooth<-2
statistic_to_use<-1 #1 is median, 2 is mean
scale_x_breaks_smooth<-experiment_doses
scale_x_labels_smooth<-experiment_doses
legend_title_smooth<-"Strain"
plot_title_smooth<-"Dose Response Curves, 21h"
xlab_smooth<-xlabel
ylab_smooth<-"Fluorescence (a.u.)"
legend_direction_smooth<-"vertical"
legend_position_smooth<-c(0.8,0.2)
additional_arguments_smooth<-NULL
time_point_smooth<-"0h" # to be used in the filename when saving the plot.

height_smooth<-10 # the height and width of the plot to be saved
width_smooth<-15
#---------------------------------------------------------------------------------------------------------------

## size plots
fscw_column_size<-1
sscw_column_size<-2
xlab_size<-"FSC-W"
ylab_size<-"SSC-W"
ylimits_size<-c(40000,NA)
xlimits_size<-c(40000,NA)

labels_for_grid_size<-time_points # labels for the plots in the 2x2 grid

height_size<-10 # saving dimensions
width_size<-15

#---------------------------------------------------------------------------------------------------------------

## histograms

doses_histogram<-experiment_doses # the doses you want to plot. if you change this, you should change the manual colour scale inside the function as well. 

labels_histogram<-c("0","0.5","1","2","3","4","5","6","7","9","10","12",
                    "14","16","18","20","23","25","27","30","45","60","100","200","fry70","tdh3",
                    "no repressor") 
breaks_histogram<-labels_histogram

dose_column<-4 #the column with doses 
citrine_column<-3 # column with citrine measurement

control_sequence<-c(3,4,5)
control_labels<-c("fry70","no repressor","tdh3")

size_histogram<- 1.3 # size of the lines
legend_title_histogram<-xlabel
legend_ncol_histogram<-2
legend_position_histogram<-c(0.7,0.8)
xlimits_histogram<-c(0,60000)
ylimits_histogram<-c(0,0.0005)

grid_labels_histograms<-time_points # labels for the plots in the 2x2 grid

height_histograms<-10 # saving dimensions
width_histograms<-15
#---------------------------------------------------------------------------------------------------------------

## descriptive plots
palette<-c("24h"="purple")
colour_labels<-time_points
scale_x_breaks<-experiment_doses
ylab_title<-"Fluorescence (a.u.)"
xlab_title<-xlabel
legend_title<-"Time Point"
stat_columns_1<-c(1,6)
stat_columns_2<-c(2,7)
size_value_descriptives<-4
height_descriptives<-10
width_descriptives<-15

#----------------------------------------------------------------------------------------------------------

## sigmoid fits
descriptives_to_use<-c(1,2)
labels_to_use<-c(1,2)
colour_palette<-c("red","blue") # define the colour palette for plotting
# define the plot title, xlabel
plot_title<-"Dose Response Curves, 24h"
xlabel<-expression(paste("aTc[ng/mL]"))

# define starting points for the fitting for each curve: c(a,b,c,d)
# a is the upper asymptote, b is the steepest slope, c is the x axis value at b, d is the lower 
# asymptote. you can define these individually for every curve.
# a negative b gives you an inverse sigmoid, a positive one gives you a sigmoid. 
list_of_starting_points<-list(
  c(30000,0.01,7,10000),
  c(20000,0.01,27,5000)
)

time_point_sigmoid<-"24h"
height_sigmoid<-10
width_sigmoid<-15
#----------------------------------------------------------------------------------------------------------
## size vs. induction plots

palette_density<-plot_palette
x_breaks_density<-labels_histogram
legend_title_density<-xlabel
ncol_legend_density<-2
legend_position_density<-c(0.15,0.68)
size_column<-5
citrine_column<-3
dose_column<-4

doses_size_vs_induction<-experiment_doses # the doses you want to plot. if you change this, you should change the manual colour scale inside the function as well. 

labels_size_vs_induction<-labels_histogram  #labels that will appear on the legend, and that determine the colour_scale_manual mappings. If you change anything here, change it in the colour scale inside the function as well. 

grid_labels_density<-time_points

height_density<-10
width_density<-15
#---------------------------------------------------------------------------------------------------------------

```


```{r}
source("facs_script.R")
library(ggplot2)

f_histograms<-function(dataframes, labels, savename){
  final_plot<-ggplot()
  
  for(i in c(1:length(dataframes))){
  single_layer<-geom_density(aes_(x=dataframes[[i]][,3], colour=labels[[i]]))
  final_plot<-final_plot+single_layer
  }
  
  pretty_plot<-final_plot +
    theme_bw() +
    xlab("Fluorescence (a.u)") +
    xlim(0,100000)
    
  ggsave(pretty_plot, filename = paste(savename, ".jpeg",sep=""), path = output_path, 
         width = 15, height = 10, unit="cm")
  
  return(pretty_plot)
}

f_histograms(df_list[c(1:4)], label_list[c(1:4)], savename="ethanol")
f_histograms(df_list[c(5:8)], label_list[c(5:8)], savename="glycerol")
f_histograms(df_list[c(9:12)], label_list[c(9:12)], savename="proline")

```


```{r sizes}

f_sizes<-function(dataframes, labels, savename){
  final_plot<-ggplot()
  
  for(i in c(1:length(dataframes))){
  single_layer<-geom_point(aes_(x=dataframes[[i]][,1],y=dataframes[[i]][,2],
                                colour=labels[[i]]), alpha=0.5)
  final_plot<-final_plot+single_layer
  }
  
  pretty_plot<-final_plot +
    theme_bw() +
    xlab("FSC-W") +
    ylab("SSC-W") 
    #xlim(0,100000)
    
  ggsave(pretty_plot, filename = paste(savename, ".jpeg",sep=""), 
         path = paste(output_path, "/size", sep=""), 
         width = 15, height = 10, unit="cm")
  
  return(pretty_plot)
}

f_sizes(df_list[c(1:4)], label_list[c(1:4)], savename="ethanol")
f_sizes(df_list[c(5:8)], label_list[c(5:8)], savename="glycerol")
f_sizes(df_list[c(9:12)], label_list[c(9:12)], savename="proline")
```

```{r size vs f}

f_sizevsf<-function(dataframes, labels, savename){
  final_plot<-ggplot()
  
  for(i in c(1:length(dataframes))){
  single_layer<-geom_density_2d(aes_(x=sqrt((dataframes[[i]][,1])^2 + (dataframes[[i]][,2])^2),
                                     y=dataframes[[i]][,3],
                                colour=labels[[i]]))
  final_plot<-final_plot+single_layer
  }
  
  pretty_plot<-final_plot +
    theme_bw() +
    xlab("size") +
    ylab("Fluorescence (a.u.)") 
    #xlim(0,100000)
    
  ggsave(pretty_plot, filename = paste(savename, ".jpeg",sep=""), 
         path = paste(output_path, "/sizevsf", sep=""), 
         width = 15, height = 10, unit="cm")
  
  return(pretty_plot)
}

f_sizevsf(df_list[c(1:4)], label_list[c(1:4)], savename="ethanol")
f_sizevsf(df_list[c(5:8)], label_list[c(5:8)], savename="glycerol")
f_sizevsf(df_list[c(9:12)], label_list[c(9:12)], savename="proline")
```